// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blood_bank_system_service.proto

package farm.nurture.farm.service.proto;

public interface AddBloodRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:farm.nurture.core.contracts.BloodBankSystemService.AddBloodRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.RequestHeaders requestHeaders = 1;</code>
   */
  boolean hasRequestHeaders();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.RequestHeaders requestHeaders = 1;</code>
   */
  farm.nurture.farm.service.proto.RequestHeaders getRequestHeaders();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.RequestHeaders requestHeaders = 1;</code>
   */
  farm.nurture.farm.service.proto.RequestHeadersOrBuilder getRequestHeadersOrBuilder();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string location = 3;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 3;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string bloodType = 4;</code>
   */
  java.lang.String getBloodType();
  /**
   * <code>string bloodType = 4;</code>
   */
  com.google.protobuf.ByteString
      getBloodTypeBytes();

  /**
   * <code>string gender = 5;</code>
   */
  java.lang.String getGender();
  /**
   * <code>string gender = 5;</code>
   */
  com.google.protobuf.ByteString
      getGenderBytes();

  /**
   * <code>string phoneNumber = 6;</code>
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>string phoneNumber = 6;</code>
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();
}
