// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blood_bank_system_service.proto

package farm.nurture.farm.service.proto;

public interface AddBloodResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:farm.nurture.core.contracts.BloodBankSystemService.AddBloodResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
   */
  boolean hasStatus();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
   */
  farm.nurture.farm.service.proto.Status getStatus();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
   */
  farm.nurture.farm.service.proto.StatusOrBuilder getStatusOrBuilder();

  /**
   * <code>int32 count = 2;</code>
   */
  int getCount();

  /**
   * <code>string recordId = 3;</code>
   */
  java.lang.String getRecordId();
  /**
   * <code>string recordId = 3;</code>
   */
  com.google.protobuf.ByteString
      getRecordIdBytes();

  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
   */
  java.util.List<farm.nurture.farm.service.proto.Attribs> 
      getAttribsList();
  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
   */
  farm.nurture.farm.service.proto.Attribs getAttribs(int index);
  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
   */
  int getAttribsCount();
  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
   */
  java.util.List<? extends farm.nurture.farm.service.proto.AttribsOrBuilder> 
      getAttribsOrBuilderList();
  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
   */
  farm.nurture.farm.service.proto.AttribsOrBuilder getAttribsOrBuilder(
      int index);
}
