// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blood_bank_system_service.proto

package farm.nurture.farm.service.proto;

/**
 * Protobuf type {@code farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse}
 */
public  final class AddUserResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse)
    AddUserResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddUserResponse.newBuilder() to construct.
  private AddUserResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddUserResponse() {
    count_ = 0;
    recordId_ = "";
    attribs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AddUserResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            farm.nurture.farm.service.proto.Status.Builder subBuilder = null;
            if (status_ != null) {
              subBuilder = status_.toBuilder();
            }
            status_ = input.readMessage(farm.nurture.farm.service.proto.Status.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(status_);
              status_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            count_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            recordId_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              attribs_ = new java.util.ArrayList<farm.nurture.farm.service.proto.Attribs>();
              mutable_bitField0_ |= 0x00000008;
            }
            attribs_.add(
                input.readMessage(farm.nurture.farm.service.proto.Attribs.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        attribs_ = java.util.Collections.unmodifiableList(attribs_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddUserResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddUserResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            farm.nurture.farm.service.proto.AddUserResponse.class, farm.nurture.farm.service.proto.AddUserResponse.Builder.class);
  }

  private int bitField0_;
  public static final int STATUS_FIELD_NUMBER = 1;
  private farm.nurture.farm.service.proto.Status status_;
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
   */
  public boolean hasStatus() {
    return status_ != null;
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
   */
  public farm.nurture.farm.service.proto.Status getStatus() {
    return status_ == null ? farm.nurture.farm.service.proto.Status.getDefaultInstance() : status_;
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
   */
  public farm.nurture.farm.service.proto.StatusOrBuilder getStatusOrBuilder() {
    return getStatus();
  }

  public static final int COUNT_FIELD_NUMBER = 2;
  private int count_;
  /**
   * <code>int32 count = 2;</code>
   */
  public int getCount() {
    return count_;
  }

  public static final int RECORDID_FIELD_NUMBER = 3;
  private volatile java.lang.Object recordId_;
  /**
   * <code>string recordId = 3;</code>
   */
  public java.lang.String getRecordId() {
    java.lang.Object ref = recordId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      recordId_ = s;
      return s;
    }
  }
  /**
   * <code>string recordId = 3;</code>
   */
  public com.google.protobuf.ByteString
      getRecordIdBytes() {
    java.lang.Object ref = recordId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      recordId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATTRIBS_FIELD_NUMBER = 4;
  private java.util.List<farm.nurture.farm.service.proto.Attribs> attribs_;
  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
   */
  public java.util.List<farm.nurture.farm.service.proto.Attribs> getAttribsList() {
    return attribs_;
  }
  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
   */
  public java.util.List<? extends farm.nurture.farm.service.proto.AttribsOrBuilder> 
      getAttribsOrBuilderList() {
    return attribs_;
  }
  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
   */
  public int getAttribsCount() {
    return attribs_.size();
  }
  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
   */
  public farm.nurture.farm.service.proto.Attribs getAttribs(int index) {
    return attribs_.get(index);
  }
  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
   */
  public farm.nurture.farm.service.proto.AttribsOrBuilder getAttribsOrBuilder(
      int index) {
    return attribs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != null) {
      output.writeMessage(1, getStatus());
    }
    if (count_ != 0) {
      output.writeInt32(2, count_);
    }
    if (!getRecordIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, recordId_);
    }
    for (int i = 0; i < attribs_.size(); i++) {
      output.writeMessage(4, attribs_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStatus());
    }
    if (count_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, count_);
    }
    if (!getRecordIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, recordId_);
    }
    for (int i = 0; i < attribs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, attribs_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof farm.nurture.farm.service.proto.AddUserResponse)) {
      return super.equals(obj);
    }
    farm.nurture.farm.service.proto.AddUserResponse other = (farm.nurture.farm.service.proto.AddUserResponse) obj;

    boolean result = true;
    result = result && (hasStatus() == other.hasStatus());
    if (hasStatus()) {
      result = result && getStatus()
          .equals(other.getStatus());
    }
    result = result && (getCount()
        == other.getCount());
    result = result && getRecordId()
        .equals(other.getRecordId());
    result = result && getAttribsList()
        .equals(other.getAttribsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    hash = (37 * hash) + COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getCount();
    hash = (37 * hash) + RECORDID_FIELD_NUMBER;
    hash = (53 * hash) + getRecordId().hashCode();
    if (getAttribsCount() > 0) {
      hash = (37 * hash) + ATTRIBS_FIELD_NUMBER;
      hash = (53 * hash) + getAttribsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static farm.nurture.farm.service.proto.AddUserResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static farm.nurture.farm.service.proto.AddUserResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.AddUserResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static farm.nurture.farm.service.proto.AddUserResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.AddUserResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static farm.nurture.farm.service.proto.AddUserResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.AddUserResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static farm.nurture.farm.service.proto.AddUserResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.AddUserResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static farm.nurture.farm.service.proto.AddUserResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.AddUserResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static farm.nurture.farm.service.proto.AddUserResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(farm.nurture.farm.service.proto.AddUserResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse)
      farm.nurture.farm.service.proto.AddUserResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddUserResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddUserResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              farm.nurture.farm.service.proto.AddUserResponse.class, farm.nurture.farm.service.proto.AddUserResponse.Builder.class);
    }

    // Construct using farm.nurture.farm.service.proto.AddUserResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAttribsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (statusBuilder_ == null) {
        status_ = null;
      } else {
        status_ = null;
        statusBuilder_ = null;
      }
      count_ = 0;

      recordId_ = "";

      if (attribsBuilder_ == null) {
        attribs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        attribsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddUserResponse_descriptor;
    }

    @java.lang.Override
    public farm.nurture.farm.service.proto.AddUserResponse getDefaultInstanceForType() {
      return farm.nurture.farm.service.proto.AddUserResponse.getDefaultInstance();
    }

    @java.lang.Override
    public farm.nurture.farm.service.proto.AddUserResponse build() {
      farm.nurture.farm.service.proto.AddUserResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public farm.nurture.farm.service.proto.AddUserResponse buildPartial() {
      farm.nurture.farm.service.proto.AddUserResponse result = new farm.nurture.farm.service.proto.AddUserResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (statusBuilder_ == null) {
        result.status_ = status_;
      } else {
        result.status_ = statusBuilder_.build();
      }
      result.count_ = count_;
      result.recordId_ = recordId_;
      if (attribsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          attribs_ = java.util.Collections.unmodifiableList(attribs_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.attribs_ = attribs_;
      } else {
        result.attribs_ = attribsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof farm.nurture.farm.service.proto.AddUserResponse) {
        return mergeFrom((farm.nurture.farm.service.proto.AddUserResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(farm.nurture.farm.service.proto.AddUserResponse other) {
      if (other == farm.nurture.farm.service.proto.AddUserResponse.getDefaultInstance()) return this;
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      if (other.getCount() != 0) {
        setCount(other.getCount());
      }
      if (!other.getRecordId().isEmpty()) {
        recordId_ = other.recordId_;
        onChanged();
      }
      if (attribsBuilder_ == null) {
        if (!other.attribs_.isEmpty()) {
          if (attribs_.isEmpty()) {
            attribs_ = other.attribs_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureAttribsIsMutable();
            attribs_.addAll(other.attribs_);
          }
          onChanged();
        }
      } else {
        if (!other.attribs_.isEmpty()) {
          if (attribsBuilder_.isEmpty()) {
            attribsBuilder_.dispose();
            attribsBuilder_ = null;
            attribs_ = other.attribs_;
            bitField0_ = (bitField0_ & ~0x00000008);
            attribsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAttribsFieldBuilder() : null;
          } else {
            attribsBuilder_.addAllMessages(other.attribs_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      farm.nurture.farm.service.proto.AddUserResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (farm.nurture.farm.service.proto.AddUserResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private farm.nurture.farm.service.proto.Status status_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.Status, farm.nurture.farm.service.proto.Status.Builder, farm.nurture.farm.service.proto.StatusOrBuilder> statusBuilder_;
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
     */
    public boolean hasStatus() {
      return statusBuilder_ != null || status_ != null;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
     */
    public farm.nurture.farm.service.proto.Status getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? farm.nurture.farm.service.proto.Status.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
     */
    public Builder setStatus(farm.nurture.farm.service.proto.Status value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
     */
    public Builder setStatus(
        farm.nurture.farm.service.proto.Status.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
     */
    public Builder mergeStatus(farm.nurture.farm.service.proto.Status value) {
      if (statusBuilder_ == null) {
        if (status_ != null) {
          status_ =
            farm.nurture.farm.service.proto.Status.newBuilder(status_).mergeFrom(value).buildPartial();
        } else {
          status_ = value;
        }
        onChanged();
      } else {
        statusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        status_ = null;
        onChanged();
      } else {
        status_ = null;
        statusBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
     */
    public farm.nurture.farm.service.proto.Status.Builder getStatusBuilder() {
      
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
     */
    public farm.nurture.farm.service.proto.StatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            farm.nurture.farm.service.proto.Status.getDefaultInstance() : status_;
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.Status, farm.nurture.farm.service.proto.Status.Builder, farm.nurture.farm.service.proto.StatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            farm.nurture.farm.service.proto.Status, farm.nurture.farm.service.proto.Status.Builder, farm.nurture.farm.service.proto.StatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    private int count_ ;
    /**
     * <code>int32 count = 2;</code>
     */
    public int getCount() {
      return count_;
    }
    /**
     * <code>int32 count = 2;</code>
     */
    public Builder setCount(int value) {
      
      count_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 count = 2;</code>
     */
    public Builder clearCount() {
      
      count_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object recordId_ = "";
    /**
     * <code>string recordId = 3;</code>
     */
    public java.lang.String getRecordId() {
      java.lang.Object ref = recordId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recordId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string recordId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRecordIdBytes() {
      java.lang.Object ref = recordId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recordId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string recordId = 3;</code>
     */
    public Builder setRecordId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      recordId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string recordId = 3;</code>
     */
    public Builder clearRecordId() {
      
      recordId_ = getDefaultInstance().getRecordId();
      onChanged();
      return this;
    }
    /**
     * <code>string recordId = 3;</code>
     */
    public Builder setRecordIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      recordId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<farm.nurture.farm.service.proto.Attribs> attribs_ =
      java.util.Collections.emptyList();
    private void ensureAttribsIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        attribs_ = new java.util.ArrayList<farm.nurture.farm.service.proto.Attribs>(attribs_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        farm.nurture.farm.service.proto.Attribs, farm.nurture.farm.service.proto.Attribs.Builder, farm.nurture.farm.service.proto.AttribsOrBuilder> attribsBuilder_;

    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
     */
    public java.util.List<farm.nurture.farm.service.proto.Attribs> getAttribsList() {
      if (attribsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(attribs_);
      } else {
        return attribsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
     */
    public int getAttribsCount() {
      if (attribsBuilder_ == null) {
        return attribs_.size();
      } else {
        return attribsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
     */
    public farm.nurture.farm.service.proto.Attribs getAttribs(int index) {
      if (attribsBuilder_ == null) {
        return attribs_.get(index);
      } else {
        return attribsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
     */
    public Builder setAttribs(
        int index, farm.nurture.farm.service.proto.Attribs value) {
      if (attribsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttribsIsMutable();
        attribs_.set(index, value);
        onChanged();
      } else {
        attribsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
     */
    public Builder setAttribs(
        int index, farm.nurture.farm.service.proto.Attribs.Builder builderForValue) {
      if (attribsBuilder_ == null) {
        ensureAttribsIsMutable();
        attribs_.set(index, builderForValue.build());
        onChanged();
      } else {
        attribsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
     */
    public Builder addAttribs(farm.nurture.farm.service.proto.Attribs value) {
      if (attribsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttribsIsMutable();
        attribs_.add(value);
        onChanged();
      } else {
        attribsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
     */
    public Builder addAttribs(
        int index, farm.nurture.farm.service.proto.Attribs value) {
      if (attribsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttribsIsMutable();
        attribs_.add(index, value);
        onChanged();
      } else {
        attribsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
     */
    public Builder addAttribs(
        farm.nurture.farm.service.proto.Attribs.Builder builderForValue) {
      if (attribsBuilder_ == null) {
        ensureAttribsIsMutable();
        attribs_.add(builderForValue.build());
        onChanged();
      } else {
        attribsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
     */
    public Builder addAttribs(
        int index, farm.nurture.farm.service.proto.Attribs.Builder builderForValue) {
      if (attribsBuilder_ == null) {
        ensureAttribsIsMutable();
        attribs_.add(index, builderForValue.build());
        onChanged();
      } else {
        attribsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
     */
    public Builder addAllAttribs(
        java.lang.Iterable<? extends farm.nurture.farm.service.proto.Attribs> values) {
      if (attribsBuilder_ == null) {
        ensureAttribsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, attribs_);
        onChanged();
      } else {
        attribsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
     */
    public Builder clearAttribs() {
      if (attribsBuilder_ == null) {
        attribs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        attribsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
     */
    public Builder removeAttribs(int index) {
      if (attribsBuilder_ == null) {
        ensureAttribsIsMutable();
        attribs_.remove(index);
        onChanged();
      } else {
        attribsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
     */
    public farm.nurture.farm.service.proto.Attribs.Builder getAttribsBuilder(
        int index) {
      return getAttribsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
     */
    public farm.nurture.farm.service.proto.AttribsOrBuilder getAttribsOrBuilder(
        int index) {
      if (attribsBuilder_ == null) {
        return attribs_.get(index);  } else {
        return attribsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
     */
    public java.util.List<? extends farm.nurture.farm.service.proto.AttribsOrBuilder> 
         getAttribsOrBuilderList() {
      if (attribsBuilder_ != null) {
        return attribsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(attribs_);
      }
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
     */
    public farm.nurture.farm.service.proto.Attribs.Builder addAttribsBuilder() {
      return getAttribsFieldBuilder().addBuilder(
          farm.nurture.farm.service.proto.Attribs.getDefaultInstance());
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
     */
    public farm.nurture.farm.service.proto.Attribs.Builder addAttribsBuilder(
        int index) {
      return getAttribsFieldBuilder().addBuilder(
          index, farm.nurture.farm.service.proto.Attribs.getDefaultInstance());
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Attribs attribs = 4;</code>
     */
    public java.util.List<farm.nurture.farm.service.proto.Attribs.Builder> 
         getAttribsBuilderList() {
      return getAttribsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        farm.nurture.farm.service.proto.Attribs, farm.nurture.farm.service.proto.Attribs.Builder, farm.nurture.farm.service.proto.AttribsOrBuilder> 
        getAttribsFieldBuilder() {
      if (attribsBuilder_ == null) {
        attribsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            farm.nurture.farm.service.proto.Attribs, farm.nurture.farm.service.proto.Attribs.Builder, farm.nurture.farm.service.proto.AttribsOrBuilder>(
                attribs_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        attribs_ = null;
      }
      return attribsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse)
  }

  // @@protoc_insertion_point(class_scope:farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse)
  private static final farm.nurture.farm.service.proto.AddUserResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new farm.nurture.farm.service.proto.AddUserResponse();
  }

  public static farm.nurture.farm.service.proto.AddUserResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddUserResponse>
      PARSER = new com.google.protobuf.AbstractParser<AddUserResponse>() {
    @java.lang.Override
    public AddUserResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AddUserResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddUserResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddUserResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public farm.nurture.farm.service.proto.AddUserResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

