// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blood_bank_system_service.proto

package farm.nurture.farm.service.proto;

public final class BloodBankSystemServiceOuterClass {
  private BloodBankSystemServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_RequestHeaders_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_nurture_core_contracts_BloodBankSystemService_RequestHeaders_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_Attribs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_nurture_core_contracts_BloodBankSystemService_Attribs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_Status_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_nurture_core_contracts_BloodBankSystemService_Status_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindPasswordRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindPasswordRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindPasswordResponseRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindPasswordResponseRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindPasswordResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindPasswordResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_BulkAddUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_nurture_core_contracts_BloodBankSystemService_BulkAddUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_BulkAddUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_nurture_core_contracts_BloodBankSystemService_BulkAddUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindBloodRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindBloodRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindBloodResponseRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindBloodResponseRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindBloodResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindBloodResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddBloodRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddBloodRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_BulkAddBloodRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_nurture_core_contracts_BloodBankSystemService_BulkAddBloodRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddBloodResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddBloodResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_BulkAddBloodResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_nurture_core_contracts_BloodBankSystemService_BulkAddBloodResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_MultiRequests_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_nurture_core_contracts_BloodBankSystemService_MultiRequests_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_nurture_core_contracts_BloodBankSystemService_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_MultiResponses_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_nurture_core_contracts_BloodBankSystemService_MultiResponses_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_nurture_core_contracts_BloodBankSystemService_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037blood_bank_system_service.proto\0222farm." +
      "nurture.core.contracts.BloodBankSystemSe" +
      "rvice\"\253\004\n\016RequestHeaders\022\031\n\021prefferedUse" +
      "rName\030\001 \001(\t\022\020\n\010clientId\030\002 \001(\t\022\021\n\ttracing" +
      "Id\030\003 \001(\t\022\024\n\014traceDetails\030\004 \001(\010\022]\n\010langua" +
      "ge\030\005 \001(\0162K.farm.nurture.core.contracts.B" +
      "loodBankSystemService.RequestHeaders.LAN" +
      "GUAGE\022\020\n\010latitude\030\006 \001(\002\022\021\n\tlongitude\030\007 \001" +
      "(\002\022\020\n\010accuracy\030\010 \001(\002\022[\n\007country\030\t \001(\0162J." +
      "farm.nurture.core.contracts.BloodBankSys" +
      "temService.RequestHeaders.COUNTRY\022\024\n\014exp" +
      "erimentId\030\n \001(\t\022L\n\007attribs\030\013 \003(\0132;.farm." +
      "nurture.core.contracts.BloodBankSystemSe" +
      "rvice.Attribs\022\021\n\tauthToken\030\014 \001(\t\022\020\n\010appT" +
      "oken\030\r \001(\t\"\"\n\010LANGUAGE\022\013\n\007English\020\000\022\t\n\005H" +
      "indi\020\002\"#\n\007COUNTRY\022\t\n\005India\020\000\022\r\n\tAustrali" +
      "a\020\002\"%\n\007Attribs\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001" +
      "(\t\"\215\001\n\006Status\022N\n\006status\030\001 \001(\0162>.farm.nur" +
      "ture.core.contracts.BloodBankSystemServi" +
      "ce.StatusCode\022\026\n\016error_messages\030\002 \003(\t\022\033\n" +
      "\023internal_error_code\030\003 \001(\005\"\225\001\n\023FindPassw" +
      "ordRequest\022Z\n\016requestHeaders\030\001 \001(\0132B.far" +
      "m.nurture.core.contracts.BloodBankSystem" +
      "Service.RequestHeaders\022\026\n\016isStaleAllowed" +
      "\030\002 \001(\010\022\n\n\002id\030\003 \001(\t\".\n\032FindPasswordRespon" +
      "seRecord\022\020\n\010password\030\001 \001(\t\"\240\002\n\024FindPassw" +
      "ordResponse\022J\n\006status\030\001 \001(\0132:.farm.nurtu" +
      "re.core.contracts.BloodBankSystemService" +
      ".Status\022\r\n\005count\030\002 \001(\005\022L\n\007attribs\030\003 \003(\0132" +
      ";.farm.nurture.core.contracts.BloodBankS" +
      "ystemService.Attribs\022_\n\007records\030\004 \003(\0132N." +
      "farm.nurture.core.contracts.BloodBankSys" +
      "temService.FindPasswordResponseRecord\"\212\001" +
      "\n\016AddUserRequest\022Z\n\016requestHeaders\030\001 \001(\013" +
      "2B.farm.nurture.core.contracts.BloodBank" +
      "SystemService.RequestHeaders\022\n\n\002id\030\002 \001(\t" +
      "\022\020\n\010password\030\003 \001(\t\"\306\001\n\022BulkAddUserReques" +
      "t\022Z\n\016requestHeaders\030\001 \001(\0132B.farm.nurture" +
      ".core.contracts.BloodBankSystemService.R" +
      "equestHeaders\022T\n\010requests\030\002 \003(\0132B.farm.n" +
      "urture.core.contracts.BloodBankSystemSer" +
      "vice.AddUserRequest\"\314\001\n\017AddUserResponse\022" +
      "J\n\006status\030\001 \001(\0132:.farm.nurture.core.cont" +
      "racts.BloodBankSystemService.Status\022\r\n\005c" +
      "ount\030\002 \001(\005\022\020\n\010recordId\030\003 \001(\t\022L\n\007attribs\030" +
      "\004 \003(\0132;.farm.nurture.core.contracts.Bloo" +
      "dBankSystemService.Attribs\"\310\001\n\023BulkAddUs" +
      "erResponse\022J\n\006status\030\001 \001(\0132:.farm.nurtur" +
      "e.core.contracts.BloodBankSystemService." +
      "Status\022\r\n\005count\030\002 \001(\005\022V\n\tresponses\030\003 \003(\013" +
      "2C.farm.nurture.core.contracts.BloodBank" +
      "SystemService.AddUserResponse\"\253\001\n\020FindBl" +
      "oodRequest\022Z\n\016requestHeaders\030\001 \001(\0132B.far" +
      "m.nurture.core.contracts.BloodBankSystem" +
      "Service.RequestHeaders\022\026\n\016isStaleAllowed" +
      "\030\002 \001(\010\022\021\n\tbloodType\030\003 \001(\t\022\020\n\010location\030\004 " +
      "\001(\t\"q\n\027FindBloodResponseRecord\022\014\n\004name\030\001" +
      " \001(\t\022\020\n\010location\030\002 \001(\t\022\021\n\tbloodType\030\003 \001(" +
      "\t\022\016\n\006gender\030\004 \001(\t\022\023\n\013phoneNumber\030\005 \001(\t\"\232" +
      "\002\n\021FindBloodResponse\022J\n\006status\030\001 \001(\0132:.f" +
      "arm.nurture.core.contracts.BloodBankSyst" +
      "emService.Status\022\r\n\005count\030\002 \001(\005\022L\n\007attri" +
      "bs\030\003 \003(\0132;.farm.nurture.core.contracts.B" +
      "loodBankSystemService.Attribs\022\\\n\007records" +
      "\030\004 \003(\0132K.farm.nurture.core.contracts.Blo" +
      "odBankSystemService.FindBloodResponseRec" +
      "ord\"\305\001\n\017AddBloodRequest\022Z\n\016requestHeader" +
      "s\030\001 \001(\0132B.farm.nurture.core.contracts.Bl" +
      "oodBankSystemService.RequestHeaders\022\014\n\004n" +
      "ame\030\002 \001(\t\022\020\n\010location\030\003 \001(\t\022\021\n\tbloodType" +
      "\030\004 \001(\t\022\016\n\006gender\030\005 \001(\t\022\023\n\013phoneNumber\030\006 " +
      "\001(\t\"\310\001\n\023BulkAddBloodRequest\022Z\n\016requestHe" +
      "aders\030\001 \001(\0132B.farm.nurture.core.contract" +
      "s.BloodBankSystemService.RequestHeaders\022" +
      "U\n\010requests\030\002 \003(\0132C.farm.nurture.core.co" +
      "ntracts.BloodBankSystemService.AddBloodR" +
      "equest\"\315\001\n\020AddBloodResponse\022J\n\006status\030\001 " +
      "\001(\0132:.farm.nurture.core.contracts.BloodB" +
      "ankSystemService.Status\022\r\n\005count\030\002 \001(\005\022\020" +
      "\n\010recordId\030\003 \001(\t\022L\n\007attribs\030\004 \003(\0132;.farm" +
      ".nurture.core.contracts.BloodBankSystemS" +
      "ervice.Attribs\"\312\001\n\024BulkAddBloodResponse\022" +
      "J\n\006status\030\001 \001(\0132:.farm.nurture.core.cont" +
      "racts.BloodBankSystemService.Status\022\r\n\005c" +
      "ount\030\002 \001(\005\022W\n\tresponses\030\003 \003(\0132D.farm.nur" +
      "ture.core.contracts.BloodBankSystemServi" +
      "ce.AddBloodResponse\"l\n\rMultiRequests\022\r\n\005" +
      "onTxn\030\001 \001(\010\022L\n\007request\030\002 \003(\0132;.farm.nurt" +
      "ure.core.contracts.BloodBankSystemServic" +
      "e.Request\"\342\004\n\007Request\022\r\n\005index\030\001 \001(\t\022b\n\017" +
      "reqFindPassword\030\002 \001(\0132G.farm.nurture.cor" +
      "e.contracts.BloodBankSystemService.FindP" +
      "asswordRequestH\000\022X\n\nreqAddUser\030\003 \001(\0132B.f" +
      "arm.nurture.core.contracts.BloodBankSyst" +
      "emService.AddUserRequestH\000\022`\n\016reqAddUser" +
      "Bulk\030\004 \001(\0132F.farm.nurture.core.contracts" +
      ".BloodBankSystemService.BulkAddUserReque" +
      "stH\000\022\\\n\014reqFindBlood\030\005 \001(\0132D.farm.nurtur" +
      "e.core.contracts.BloodBankSystemService." +
      "FindBloodRequestH\000\022Z\n\013reqAddBlood\030\006 \001(\0132" +
      "C.farm.nurture.core.contracts.BloodBankS" +
      "ystemService.AddBloodRequestH\000\022b\n\017reqAdd" +
      "BloodBulk\030\007 \001(\0132G.farm.nurture.core.cont" +
      "racts.BloodBankSystemService.BulkAddBloo" +
      "dRequestH\000B\n\n\010ARequest\"\254\001\n\016MultiResponse" +
      "s\022J\n\006status\030\001 \001(\0132:.farm.nurture.core.co" +
      "ntracts.BloodBankSystemService.Status\022N\n" +
      "\010response\030\002 \003(\0132<.farm.nurture.core.cont" +
      "racts.BloodBankSystemService.Response\"\266\005" +
      "\n\010Response\022\r\n\005index\030\001 \001(\t\022J\n\006status\030\002 \001(" +
      "\0132:.farm.nurture.core.contracts.BloodBan" +
      "kSystemService.Status\022c\n\017resFindPassword" +
      "\030\003 \001(\0132H.farm.nurture.core.contracts.Blo" +
      "odBankSystemService.FindPasswordResponse" +
      "H\000\022Y\n\nresAddUser\030\004 \001(\0132C.farm.nurture.co" +
      "re.contracts.BloodBankSystemService.AddU" +
      "serResponseH\000\022a\n\016resAddUserBulk\030\005 \001(\0132G." +
      "farm.nurture.core.contracts.BloodBankSys" +
      "temService.BulkAddUserResponseH\000\022]\n\014resF" +
      "indBlood\030\006 \001(\0132E.farm.nurture.core.contr" +
      "acts.BloodBankSystemService.FindBloodRes" +
      "ponseH\000\022[\n\013resAddBlood\030\007 \001(\0132D.farm.nurt" +
      "ure.core.contracts.BloodBankSystemServic" +
      "e.AddBloodResponseH\000\022c\n\017resAddBloodBulk\030" +
      "\010 \001(\0132H.farm.nurture.core.contracts.Bloo" +
      "dBankSystemService.BulkAddBloodResponseH" +
      "\000B\013\n\tAResponse*\332\001\n\nStatusCode\022\013\n\007SUCCESS" +
      "\020\000\022\r\n\tNOT_FOUND\020\001\022\020\n\014ZERO_RESULTS\020\002\022\r\n\tD" +
      "UPLICATE\020\003\022\022\n\016LIMIT_EXCEEDED\020\004\022\023\n\017INVALI" +
      "D_REQUEST\020\005\022\031\n\025TEMPORARILY_SUSPENDED\020\006\022\024" +
      "\n\020OVER_USAGE_LIMIT\020\007\022\022\n\016REQUEST_DENIED\020\010" +
      "\022\021\n\rUNKNOWN_ERROR\020\t\022\016\n\nDB_FAILURE\020\n2\224\t\n\026" +
      "BloodBankSystemService\022\252\001\n\023ExecuteFindPa" +
      "ssword\022G.farm.nurture.core.contracts.Blo" +
      "odBankSystemService.FindPasswordRequest\032" +
      "H.farm.nurture.core.contracts.BloodBankS" +
      "ystemService.FindPasswordResponse\"\000\022\233\001\n\016" +
      "ExecuteAddUser\022B.farm.nurture.core.contr" +
      "acts.BloodBankSystemService.AddUserReque" +
      "st\032C.farm.nurture.core.contracts.BloodBa" +
      "nkSystemService.AddUserResponse\"\000\022\247\001\n\022Ex" +
      "ecuteAddUserBulk\022F.farm.nurture.core.con" +
      "tracts.BloodBankSystemService.BulkAddUse" +
      "rRequest\032G.farm.nurture.core.contracts.B" +
      "loodBankSystemService.BulkAddUserRespons" +
      "e\"\000\022\241\001\n\020ExecuteFindBlood\022D.farm.nurture." +
      "core.contracts.BloodBankSystemService.Fi" +
      "ndBloodRequest\032E.farm.nurture.core.contr" +
      "acts.BloodBankSystemService.FindBloodRes" +
      "ponse\"\000\022\236\001\n\017ExecuteAddBlood\022C.farm.nurtu" +
      "re.core.contracts.BloodBankSystemService" +
      ".AddBloodRequest\032D.farm.nurture.core.con" +
      "tracts.BloodBankSystemService.AddBloodRe" +
      "sponse\"\000\022\252\001\n\023ExecuteAddBloodBulk\022G.farm." +
      "nurture.core.contracts.BloodBankSystemSe" +
      "rvice.BulkAddBloodRequest\032H.farm.nurture" +
      ".core.contracts.BloodBankSystemService.B" +
      "ulkAddBloodResponse\"\000\022\222\001\n\007Execute\022A.farm" +
      ".nurture.core.contracts.BloodBankSystemS" +
      "ervice.MultiRequests\032B.farm.nurture.core" +
      ".contracts.BloodBankSystemService.MultiR" +
      "esponses\"\000BR\n\037farm.nurture.farm.service." +
      "protoP\001Z-BloodBankSystemService/BloodBan" +
      "kSystemServiceb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_RequestHeaders_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_RequestHeaders_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_nurture_core_contracts_BloodBankSystemService_RequestHeaders_descriptor,
        new java.lang.String[] { "PrefferedUserName", "ClientId", "TracingId", "TraceDetails", "Language", "Latitude", "Longitude", "Accuracy", "Country", "ExperimentId", "Attribs", "AuthToken", "AppToken", });
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_Attribs_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_Attribs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_nurture_core_contracts_BloodBankSystemService_Attribs_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_Status_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_nurture_core_contracts_BloodBankSystemService_Status_descriptor,
        new java.lang.String[] { "Status", "ErrorMessages", "InternalErrorCode", });
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindPasswordRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindPasswordRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindPasswordRequest_descriptor,
        new java.lang.String[] { "RequestHeaders", "IsStaleAllowed", "Id", });
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindPasswordResponseRecord_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindPasswordResponseRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindPasswordResponseRecord_descriptor,
        new java.lang.String[] { "Password", });
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindPasswordResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindPasswordResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindPasswordResponse_descriptor,
        new java.lang.String[] { "Status", "Count", "Attribs", "Records", });
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddUserRequest_descriptor,
        new java.lang.String[] { "RequestHeaders", "Id", "Password", });
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_BulkAddUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_BulkAddUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_nurture_core_contracts_BloodBankSystemService_BulkAddUserRequest_descriptor,
        new java.lang.String[] { "RequestHeaders", "Requests", });
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddUserResponse_descriptor,
        new java.lang.String[] { "Status", "Count", "RecordId", "Attribs", });
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_BulkAddUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_BulkAddUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_nurture_core_contracts_BloodBankSystemService_BulkAddUserResponse_descriptor,
        new java.lang.String[] { "Status", "Count", "Responses", });
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindBloodRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindBloodRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindBloodRequest_descriptor,
        new java.lang.String[] { "RequestHeaders", "IsStaleAllowed", "BloodType", "Location", });
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindBloodResponseRecord_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindBloodResponseRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindBloodResponseRecord_descriptor,
        new java.lang.String[] { "Name", "Location", "BloodType", "Gender", "PhoneNumber", });
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindBloodResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindBloodResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_nurture_core_contracts_BloodBankSystemService_FindBloodResponse_descriptor,
        new java.lang.String[] { "Status", "Count", "Attribs", "Records", });
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddBloodRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddBloodRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddBloodRequest_descriptor,
        new java.lang.String[] { "RequestHeaders", "Name", "Location", "BloodType", "Gender", "PhoneNumber", });
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_BulkAddBloodRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_BulkAddBloodRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_nurture_core_contracts_BloodBankSystemService_BulkAddBloodRequest_descriptor,
        new java.lang.String[] { "RequestHeaders", "Requests", });
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddBloodResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddBloodResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_nurture_core_contracts_BloodBankSystemService_AddBloodResponse_descriptor,
        new java.lang.String[] { "Status", "Count", "RecordId", "Attribs", });
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_BulkAddBloodResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_BulkAddBloodResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_nurture_core_contracts_BloodBankSystemService_BulkAddBloodResponse_descriptor,
        new java.lang.String[] { "Status", "Count", "Responses", });
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_MultiRequests_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_MultiRequests_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_nurture_core_contracts_BloodBankSystemService_MultiRequests_descriptor,
        new java.lang.String[] { "OnTxn", "Request", });
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_Request_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_nurture_core_contracts_BloodBankSystemService_Request_descriptor,
        new java.lang.String[] { "Index", "ReqFindPassword", "ReqAddUser", "ReqAddUserBulk", "ReqFindBlood", "ReqAddBlood", "ReqAddBloodBulk", "ARequest", });
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_MultiResponses_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_MultiResponses_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_nurture_core_contracts_BloodBankSystemService_MultiResponses_descriptor,
        new java.lang.String[] { "Status", "Response", });
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_Response_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_farm_nurture_core_contracts_BloodBankSystemService_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_nurture_core_contracts_BloodBankSystemService_Response_descriptor,
        new java.lang.String[] { "Index", "Status", "ResFindPassword", "ResAddUser", "ResAddUserBulk", "ResFindBlood", "ResAddBlood", "ResAddBloodBulk", "AResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
