// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blood_bank_system_service.proto

package farm.nurture.farm.service.proto;

public interface BulkAddUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
   */
  boolean hasStatus();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
   */
  farm.nurture.farm.service.proto.Status getStatus();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
   */
  farm.nurture.farm.service.proto.StatusOrBuilder getStatusOrBuilder();

  /**
   * <code>int32 count = 2;</code>
   */
  int getCount();

  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse responses = 3;</code>
   */
  java.util.List<farm.nurture.farm.service.proto.AddUserResponse> 
      getResponsesList();
  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse responses = 3;</code>
   */
  farm.nurture.farm.service.proto.AddUserResponse getResponses(int index);
  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse responses = 3;</code>
   */
  int getResponsesCount();
  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse responses = 3;</code>
   */
  java.util.List<? extends farm.nurture.farm.service.proto.AddUserResponseOrBuilder> 
      getResponsesOrBuilderList();
  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse responses = 3;</code>
   */
  farm.nurture.farm.service.proto.AddUserResponseOrBuilder getResponsesOrBuilder(
      int index);
}
