// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blood_bank_system_service.proto

package farm.nurture.farm.service.proto;

public interface FindPasswordRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:farm.nurture.core.contracts.BloodBankSystemService.FindPasswordRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.RequestHeaders requestHeaders = 1;</code>
   */
  boolean hasRequestHeaders();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.RequestHeaders requestHeaders = 1;</code>
   */
  farm.nurture.farm.service.proto.RequestHeaders getRequestHeaders();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.RequestHeaders requestHeaders = 1;</code>
   */
  farm.nurture.farm.service.proto.RequestHeadersOrBuilder getRequestHeadersOrBuilder();

  /**
   * <code>bool isStaleAllowed = 2;</code>
   */
  boolean getIsStaleAllowed();

  /**
   * <code>string id = 3;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 3;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
