// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blood_bank_system_service.proto

package farm.nurture.farm.service.proto;

public interface MultiResponsesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:farm.nurture.core.contracts.BloodBankSystemService.MultiResponses)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
   */
  boolean hasStatus();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
   */
  farm.nurture.farm.service.proto.Status getStatus();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
   */
  farm.nurture.farm.service.proto.StatusOrBuilder getStatusOrBuilder();

  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
   */
  java.util.List<farm.nurture.farm.service.proto.Response> 
      getResponseList();
  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
   */
  farm.nurture.farm.service.proto.Response getResponse(int index);
  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
   */
  int getResponseCount();
  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
   */
  java.util.List<? extends farm.nurture.farm.service.proto.ResponseOrBuilder> 
      getResponseOrBuilderList();
  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
   */
  farm.nurture.farm.service.proto.ResponseOrBuilder getResponseOrBuilder(
      int index);
}
