// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blood_bank_system_service.proto

package farm.nurture.farm.service.proto;

/**
 * Protobuf type {@code farm.nurture.core.contracts.BloodBankSystemService.MultiResponses}
 */
public  final class MultiResponses extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:farm.nurture.core.contracts.BloodBankSystemService.MultiResponses)
    MultiResponsesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MultiResponses.newBuilder() to construct.
  private MultiResponses(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MultiResponses() {
    response_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MultiResponses(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            farm.nurture.farm.service.proto.Status.Builder subBuilder = null;
            if (status_ != null) {
              subBuilder = status_.toBuilder();
            }
            status_ = input.readMessage(farm.nurture.farm.service.proto.Status.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(status_);
              status_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              response_ = new java.util.ArrayList<farm.nurture.farm.service.proto.Response>();
              mutable_bitField0_ |= 0x00000002;
            }
            response_.add(
                input.readMessage(farm.nurture.farm.service.proto.Response.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        response_ = java.util.Collections.unmodifiableList(response_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_MultiResponses_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_MultiResponses_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            farm.nurture.farm.service.proto.MultiResponses.class, farm.nurture.farm.service.proto.MultiResponses.Builder.class);
  }

  private int bitField0_;
  public static final int STATUS_FIELD_NUMBER = 1;
  private farm.nurture.farm.service.proto.Status status_;
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
   */
  public boolean hasStatus() {
    return status_ != null;
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
   */
  public farm.nurture.farm.service.proto.Status getStatus() {
    return status_ == null ? farm.nurture.farm.service.proto.Status.getDefaultInstance() : status_;
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
   */
  public farm.nurture.farm.service.proto.StatusOrBuilder getStatusOrBuilder() {
    return getStatus();
  }

  public static final int RESPONSE_FIELD_NUMBER = 2;
  private java.util.List<farm.nurture.farm.service.proto.Response> response_;
  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
   */
  public java.util.List<farm.nurture.farm.service.proto.Response> getResponseList() {
    return response_;
  }
  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
   */
  public java.util.List<? extends farm.nurture.farm.service.proto.ResponseOrBuilder> 
      getResponseOrBuilderList() {
    return response_;
  }
  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
   */
  public int getResponseCount() {
    return response_.size();
  }
  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
   */
  public farm.nurture.farm.service.proto.Response getResponse(int index) {
    return response_.get(index);
  }
  /**
   * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
   */
  public farm.nurture.farm.service.proto.ResponseOrBuilder getResponseOrBuilder(
      int index) {
    return response_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != null) {
      output.writeMessage(1, getStatus());
    }
    for (int i = 0; i < response_.size(); i++) {
      output.writeMessage(2, response_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStatus());
    }
    for (int i = 0; i < response_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, response_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof farm.nurture.farm.service.proto.MultiResponses)) {
      return super.equals(obj);
    }
    farm.nurture.farm.service.proto.MultiResponses other = (farm.nurture.farm.service.proto.MultiResponses) obj;

    boolean result = true;
    result = result && (hasStatus() == other.hasStatus());
    if (hasStatus()) {
      result = result && getStatus()
          .equals(other.getStatus());
    }
    result = result && getResponseList()
        .equals(other.getResponseList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    if (getResponseCount() > 0) {
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static farm.nurture.farm.service.proto.MultiResponses parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static farm.nurture.farm.service.proto.MultiResponses parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.MultiResponses parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static farm.nurture.farm.service.proto.MultiResponses parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.MultiResponses parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static farm.nurture.farm.service.proto.MultiResponses parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.MultiResponses parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static farm.nurture.farm.service.proto.MultiResponses parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.MultiResponses parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static farm.nurture.farm.service.proto.MultiResponses parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.MultiResponses parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static farm.nurture.farm.service.proto.MultiResponses parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(farm.nurture.farm.service.proto.MultiResponses prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code farm.nurture.core.contracts.BloodBankSystemService.MultiResponses}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:farm.nurture.core.contracts.BloodBankSystemService.MultiResponses)
      farm.nurture.farm.service.proto.MultiResponsesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_MultiResponses_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_MultiResponses_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              farm.nurture.farm.service.proto.MultiResponses.class, farm.nurture.farm.service.proto.MultiResponses.Builder.class);
    }

    // Construct using farm.nurture.farm.service.proto.MultiResponses.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResponseFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (statusBuilder_ == null) {
        status_ = null;
      } else {
        status_ = null;
        statusBuilder_ = null;
      }
      if (responseBuilder_ == null) {
        response_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        responseBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_MultiResponses_descriptor;
    }

    @java.lang.Override
    public farm.nurture.farm.service.proto.MultiResponses getDefaultInstanceForType() {
      return farm.nurture.farm.service.proto.MultiResponses.getDefaultInstance();
    }

    @java.lang.Override
    public farm.nurture.farm.service.proto.MultiResponses build() {
      farm.nurture.farm.service.proto.MultiResponses result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public farm.nurture.farm.service.proto.MultiResponses buildPartial() {
      farm.nurture.farm.service.proto.MultiResponses result = new farm.nurture.farm.service.proto.MultiResponses(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (statusBuilder_ == null) {
        result.status_ = status_;
      } else {
        result.status_ = statusBuilder_.build();
      }
      if (responseBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          response_ = java.util.Collections.unmodifiableList(response_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.response_ = response_;
      } else {
        result.response_ = responseBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof farm.nurture.farm.service.proto.MultiResponses) {
        return mergeFrom((farm.nurture.farm.service.proto.MultiResponses)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(farm.nurture.farm.service.proto.MultiResponses other) {
      if (other == farm.nurture.farm.service.proto.MultiResponses.getDefaultInstance()) return this;
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      if (responseBuilder_ == null) {
        if (!other.response_.isEmpty()) {
          if (response_.isEmpty()) {
            response_ = other.response_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureResponseIsMutable();
            response_.addAll(other.response_);
          }
          onChanged();
        }
      } else {
        if (!other.response_.isEmpty()) {
          if (responseBuilder_.isEmpty()) {
            responseBuilder_.dispose();
            responseBuilder_ = null;
            response_ = other.response_;
            bitField0_ = (bitField0_ & ~0x00000002);
            responseBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getResponseFieldBuilder() : null;
          } else {
            responseBuilder_.addAllMessages(other.response_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      farm.nurture.farm.service.proto.MultiResponses parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (farm.nurture.farm.service.proto.MultiResponses) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private farm.nurture.farm.service.proto.Status status_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.Status, farm.nurture.farm.service.proto.Status.Builder, farm.nurture.farm.service.proto.StatusOrBuilder> statusBuilder_;
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
     */
    public boolean hasStatus() {
      return statusBuilder_ != null || status_ != null;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
     */
    public farm.nurture.farm.service.proto.Status getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? farm.nurture.farm.service.proto.Status.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
     */
    public Builder setStatus(farm.nurture.farm.service.proto.Status value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
     */
    public Builder setStatus(
        farm.nurture.farm.service.proto.Status.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
     */
    public Builder mergeStatus(farm.nurture.farm.service.proto.Status value) {
      if (statusBuilder_ == null) {
        if (status_ != null) {
          status_ =
            farm.nurture.farm.service.proto.Status.newBuilder(status_).mergeFrom(value).buildPartial();
        } else {
          status_ = value;
        }
        onChanged();
      } else {
        statusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        status_ = null;
        onChanged();
      } else {
        status_ = null;
        statusBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
     */
    public farm.nurture.farm.service.proto.Status.Builder getStatusBuilder() {
      
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
     */
    public farm.nurture.farm.service.proto.StatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            farm.nurture.farm.service.proto.Status.getDefaultInstance() : status_;
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.Status, farm.nurture.farm.service.proto.Status.Builder, farm.nurture.farm.service.proto.StatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            farm.nurture.farm.service.proto.Status, farm.nurture.farm.service.proto.Status.Builder, farm.nurture.farm.service.proto.StatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    private java.util.List<farm.nurture.farm.service.proto.Response> response_ =
      java.util.Collections.emptyList();
    private void ensureResponseIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        response_ = new java.util.ArrayList<farm.nurture.farm.service.proto.Response>(response_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        farm.nurture.farm.service.proto.Response, farm.nurture.farm.service.proto.Response.Builder, farm.nurture.farm.service.proto.ResponseOrBuilder> responseBuilder_;

    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
     */
    public java.util.List<farm.nurture.farm.service.proto.Response> getResponseList() {
      if (responseBuilder_ == null) {
        return java.util.Collections.unmodifiableList(response_);
      } else {
        return responseBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
     */
    public int getResponseCount() {
      if (responseBuilder_ == null) {
        return response_.size();
      } else {
        return responseBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
     */
    public farm.nurture.farm.service.proto.Response getResponse(int index) {
      if (responseBuilder_ == null) {
        return response_.get(index);
      } else {
        return responseBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
     */
    public Builder setResponse(
        int index, farm.nurture.farm.service.proto.Response value) {
      if (responseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResponseIsMutable();
        response_.set(index, value);
        onChanged();
      } else {
        responseBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
     */
    public Builder setResponse(
        int index, farm.nurture.farm.service.proto.Response.Builder builderForValue) {
      if (responseBuilder_ == null) {
        ensureResponseIsMutable();
        response_.set(index, builderForValue.build());
        onChanged();
      } else {
        responseBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
     */
    public Builder addResponse(farm.nurture.farm.service.proto.Response value) {
      if (responseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResponseIsMutable();
        response_.add(value);
        onChanged();
      } else {
        responseBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
     */
    public Builder addResponse(
        int index, farm.nurture.farm.service.proto.Response value) {
      if (responseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResponseIsMutable();
        response_.add(index, value);
        onChanged();
      } else {
        responseBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
     */
    public Builder addResponse(
        farm.nurture.farm.service.proto.Response.Builder builderForValue) {
      if (responseBuilder_ == null) {
        ensureResponseIsMutable();
        response_.add(builderForValue.build());
        onChanged();
      } else {
        responseBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
     */
    public Builder addResponse(
        int index, farm.nurture.farm.service.proto.Response.Builder builderForValue) {
      if (responseBuilder_ == null) {
        ensureResponseIsMutable();
        response_.add(index, builderForValue.build());
        onChanged();
      } else {
        responseBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
     */
    public Builder addAllResponse(
        java.lang.Iterable<? extends farm.nurture.farm.service.proto.Response> values) {
      if (responseBuilder_ == null) {
        ensureResponseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, response_);
        onChanged();
      } else {
        responseBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
     */
    public Builder clearResponse() {
      if (responseBuilder_ == null) {
        response_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        responseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
     */
    public Builder removeResponse(int index) {
      if (responseBuilder_ == null) {
        ensureResponseIsMutable();
        response_.remove(index);
        onChanged();
      } else {
        responseBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
     */
    public farm.nurture.farm.service.proto.Response.Builder getResponseBuilder(
        int index) {
      return getResponseFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
     */
    public farm.nurture.farm.service.proto.ResponseOrBuilder getResponseOrBuilder(
        int index) {
      if (responseBuilder_ == null) {
        return response_.get(index);  } else {
        return responseBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
     */
    public java.util.List<? extends farm.nurture.farm.service.proto.ResponseOrBuilder> 
         getResponseOrBuilderList() {
      if (responseBuilder_ != null) {
        return responseBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(response_);
      }
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
     */
    public farm.nurture.farm.service.proto.Response.Builder addResponseBuilder() {
      return getResponseFieldBuilder().addBuilder(
          farm.nurture.farm.service.proto.Response.getDefaultInstance());
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
     */
    public farm.nurture.farm.service.proto.Response.Builder addResponseBuilder(
        int index) {
      return getResponseFieldBuilder().addBuilder(
          index, farm.nurture.farm.service.proto.Response.getDefaultInstance());
    }
    /**
     * <code>repeated .farm.nurture.core.contracts.BloodBankSystemService.Response response = 2;</code>
     */
    public java.util.List<farm.nurture.farm.service.proto.Response.Builder> 
         getResponseBuilderList() {
      return getResponseFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        farm.nurture.farm.service.proto.Response, farm.nurture.farm.service.proto.Response.Builder, farm.nurture.farm.service.proto.ResponseOrBuilder> 
        getResponseFieldBuilder() {
      if (responseBuilder_ == null) {
        responseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            farm.nurture.farm.service.proto.Response, farm.nurture.farm.service.proto.Response.Builder, farm.nurture.farm.service.proto.ResponseOrBuilder>(
                response_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      return responseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:farm.nurture.core.contracts.BloodBankSystemService.MultiResponses)
  }

  // @@protoc_insertion_point(class_scope:farm.nurture.core.contracts.BloodBankSystemService.MultiResponses)
  private static final farm.nurture.farm.service.proto.MultiResponses DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new farm.nurture.farm.service.proto.MultiResponses();
  }

  public static farm.nurture.farm.service.proto.MultiResponses getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MultiResponses>
      PARSER = new com.google.protobuf.AbstractParser<MultiResponses>() {
    @java.lang.Override
    public MultiResponses parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MultiResponses(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MultiResponses> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MultiResponses> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public farm.nurture.farm.service.proto.MultiResponses getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

