// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blood_bank_system_service.proto

package farm.nurture.farm.service.proto;

/**
 * Protobuf type {@code farm.nurture.core.contracts.BloodBankSystemService.Request}
 */
public  final class Request extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:farm.nurture.core.contracts.BloodBankSystemService.Request)
    RequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Request.newBuilder() to construct.
  private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Request() {
    index_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Request(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            index_ = s;
            break;
          }
          case 18: {
            farm.nurture.farm.service.proto.FindPasswordRequest.Builder subBuilder = null;
            if (aRequestCase_ == 2) {
              subBuilder = ((farm.nurture.farm.service.proto.FindPasswordRequest) aRequest_).toBuilder();
            }
            aRequest_ =
                input.readMessage(farm.nurture.farm.service.proto.FindPasswordRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((farm.nurture.farm.service.proto.FindPasswordRequest) aRequest_);
              aRequest_ = subBuilder.buildPartial();
            }
            aRequestCase_ = 2;
            break;
          }
          case 26: {
            farm.nurture.farm.service.proto.AddUserRequest.Builder subBuilder = null;
            if (aRequestCase_ == 3) {
              subBuilder = ((farm.nurture.farm.service.proto.AddUserRequest) aRequest_).toBuilder();
            }
            aRequest_ =
                input.readMessage(farm.nurture.farm.service.proto.AddUserRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((farm.nurture.farm.service.proto.AddUserRequest) aRequest_);
              aRequest_ = subBuilder.buildPartial();
            }
            aRequestCase_ = 3;
            break;
          }
          case 34: {
            farm.nurture.farm.service.proto.BulkAddUserRequest.Builder subBuilder = null;
            if (aRequestCase_ == 4) {
              subBuilder = ((farm.nurture.farm.service.proto.BulkAddUserRequest) aRequest_).toBuilder();
            }
            aRequest_ =
                input.readMessage(farm.nurture.farm.service.proto.BulkAddUserRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((farm.nurture.farm.service.proto.BulkAddUserRequest) aRequest_);
              aRequest_ = subBuilder.buildPartial();
            }
            aRequestCase_ = 4;
            break;
          }
          case 42: {
            farm.nurture.farm.service.proto.FindBloodRequest.Builder subBuilder = null;
            if (aRequestCase_ == 5) {
              subBuilder = ((farm.nurture.farm.service.proto.FindBloodRequest) aRequest_).toBuilder();
            }
            aRequest_ =
                input.readMessage(farm.nurture.farm.service.proto.FindBloodRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((farm.nurture.farm.service.proto.FindBloodRequest) aRequest_);
              aRequest_ = subBuilder.buildPartial();
            }
            aRequestCase_ = 5;
            break;
          }
          case 50: {
            farm.nurture.farm.service.proto.AddBloodRequest.Builder subBuilder = null;
            if (aRequestCase_ == 6) {
              subBuilder = ((farm.nurture.farm.service.proto.AddBloodRequest) aRequest_).toBuilder();
            }
            aRequest_ =
                input.readMessage(farm.nurture.farm.service.proto.AddBloodRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((farm.nurture.farm.service.proto.AddBloodRequest) aRequest_);
              aRequest_ = subBuilder.buildPartial();
            }
            aRequestCase_ = 6;
            break;
          }
          case 58: {
            farm.nurture.farm.service.proto.BulkAddBloodRequest.Builder subBuilder = null;
            if (aRequestCase_ == 7) {
              subBuilder = ((farm.nurture.farm.service.proto.BulkAddBloodRequest) aRequest_).toBuilder();
            }
            aRequest_ =
                input.readMessage(farm.nurture.farm.service.proto.BulkAddBloodRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((farm.nurture.farm.service.proto.BulkAddBloodRequest) aRequest_);
              aRequest_ = subBuilder.buildPartial();
            }
            aRequestCase_ = 7;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_Request_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_Request_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            farm.nurture.farm.service.proto.Request.class, farm.nurture.farm.service.proto.Request.Builder.class);
  }

  private int aRequestCase_ = 0;
  private java.lang.Object aRequest_;
  public enum ARequestCase
      implements com.google.protobuf.Internal.EnumLite {
    REQFINDPASSWORD(2),
    REQADDUSER(3),
    REQADDUSERBULK(4),
    REQFINDBLOOD(5),
    REQADDBLOOD(6),
    REQADDBLOODBULK(7),
    AREQUEST_NOT_SET(0);
    private final int value;
    private ARequestCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ARequestCase valueOf(int value) {
      return forNumber(value);
    }

    public static ARequestCase forNumber(int value) {
      switch (value) {
        case 2: return REQFINDPASSWORD;
        case 3: return REQADDUSER;
        case 4: return REQADDUSERBULK;
        case 5: return REQFINDBLOOD;
        case 6: return REQADDBLOOD;
        case 7: return REQADDBLOODBULK;
        case 0: return AREQUEST_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ARequestCase
  getARequestCase() {
    return ARequestCase.forNumber(
        aRequestCase_);
  }

  public static final int INDEX_FIELD_NUMBER = 1;
  private volatile java.lang.Object index_;
  /**
   * <code>string index = 1;</code>
   */
  public java.lang.String getIndex() {
    java.lang.Object ref = index_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      index_ = s;
      return s;
    }
  }
  /**
   * <code>string index = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIndexBytes() {
    java.lang.Object ref = index_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      index_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQFINDPASSWORD_FIELD_NUMBER = 2;
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordRequest reqFindPassword = 2;</code>
   */
  public boolean hasReqFindPassword() {
    return aRequestCase_ == 2;
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordRequest reqFindPassword = 2;</code>
   */
  public farm.nurture.farm.service.proto.FindPasswordRequest getReqFindPassword() {
    if (aRequestCase_ == 2) {
       return (farm.nurture.farm.service.proto.FindPasswordRequest) aRequest_;
    }
    return farm.nurture.farm.service.proto.FindPasswordRequest.getDefaultInstance();
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordRequest reqFindPassword = 2;</code>
   */
  public farm.nurture.farm.service.proto.FindPasswordRequestOrBuilder getReqFindPasswordOrBuilder() {
    if (aRequestCase_ == 2) {
       return (farm.nurture.farm.service.proto.FindPasswordRequest) aRequest_;
    }
    return farm.nurture.farm.service.proto.FindPasswordRequest.getDefaultInstance();
  }

  public static final int REQADDUSER_FIELD_NUMBER = 3;
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserRequest reqAddUser = 3;</code>
   */
  public boolean hasReqAddUser() {
    return aRequestCase_ == 3;
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserRequest reqAddUser = 3;</code>
   */
  public farm.nurture.farm.service.proto.AddUserRequest getReqAddUser() {
    if (aRequestCase_ == 3) {
       return (farm.nurture.farm.service.proto.AddUserRequest) aRequest_;
    }
    return farm.nurture.farm.service.proto.AddUserRequest.getDefaultInstance();
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserRequest reqAddUser = 3;</code>
   */
  public farm.nurture.farm.service.proto.AddUserRequestOrBuilder getReqAddUserOrBuilder() {
    if (aRequestCase_ == 3) {
       return (farm.nurture.farm.service.proto.AddUserRequest) aRequest_;
    }
    return farm.nurture.farm.service.proto.AddUserRequest.getDefaultInstance();
  }

  public static final int REQADDUSERBULK_FIELD_NUMBER = 4;
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserRequest reqAddUserBulk = 4;</code>
   */
  public boolean hasReqAddUserBulk() {
    return aRequestCase_ == 4;
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserRequest reqAddUserBulk = 4;</code>
   */
  public farm.nurture.farm.service.proto.BulkAddUserRequest getReqAddUserBulk() {
    if (aRequestCase_ == 4) {
       return (farm.nurture.farm.service.proto.BulkAddUserRequest) aRequest_;
    }
    return farm.nurture.farm.service.proto.BulkAddUserRequest.getDefaultInstance();
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserRequest reqAddUserBulk = 4;</code>
   */
  public farm.nurture.farm.service.proto.BulkAddUserRequestOrBuilder getReqAddUserBulkOrBuilder() {
    if (aRequestCase_ == 4) {
       return (farm.nurture.farm.service.proto.BulkAddUserRequest) aRequest_;
    }
    return farm.nurture.farm.service.proto.BulkAddUserRequest.getDefaultInstance();
  }

  public static final int REQFINDBLOOD_FIELD_NUMBER = 5;
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodRequest reqFindBlood = 5;</code>
   */
  public boolean hasReqFindBlood() {
    return aRequestCase_ == 5;
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodRequest reqFindBlood = 5;</code>
   */
  public farm.nurture.farm.service.proto.FindBloodRequest getReqFindBlood() {
    if (aRequestCase_ == 5) {
       return (farm.nurture.farm.service.proto.FindBloodRequest) aRequest_;
    }
    return farm.nurture.farm.service.proto.FindBloodRequest.getDefaultInstance();
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodRequest reqFindBlood = 5;</code>
   */
  public farm.nurture.farm.service.proto.FindBloodRequestOrBuilder getReqFindBloodOrBuilder() {
    if (aRequestCase_ == 5) {
       return (farm.nurture.farm.service.proto.FindBloodRequest) aRequest_;
    }
    return farm.nurture.farm.service.proto.FindBloodRequest.getDefaultInstance();
  }

  public static final int REQADDBLOOD_FIELD_NUMBER = 6;
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodRequest reqAddBlood = 6;</code>
   */
  public boolean hasReqAddBlood() {
    return aRequestCase_ == 6;
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodRequest reqAddBlood = 6;</code>
   */
  public farm.nurture.farm.service.proto.AddBloodRequest getReqAddBlood() {
    if (aRequestCase_ == 6) {
       return (farm.nurture.farm.service.proto.AddBloodRequest) aRequest_;
    }
    return farm.nurture.farm.service.proto.AddBloodRequest.getDefaultInstance();
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodRequest reqAddBlood = 6;</code>
   */
  public farm.nurture.farm.service.proto.AddBloodRequestOrBuilder getReqAddBloodOrBuilder() {
    if (aRequestCase_ == 6) {
       return (farm.nurture.farm.service.proto.AddBloodRequest) aRequest_;
    }
    return farm.nurture.farm.service.proto.AddBloodRequest.getDefaultInstance();
  }

  public static final int REQADDBLOODBULK_FIELD_NUMBER = 7;
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodRequest reqAddBloodBulk = 7;</code>
   */
  public boolean hasReqAddBloodBulk() {
    return aRequestCase_ == 7;
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodRequest reqAddBloodBulk = 7;</code>
   */
  public farm.nurture.farm.service.proto.BulkAddBloodRequest getReqAddBloodBulk() {
    if (aRequestCase_ == 7) {
       return (farm.nurture.farm.service.proto.BulkAddBloodRequest) aRequest_;
    }
    return farm.nurture.farm.service.proto.BulkAddBloodRequest.getDefaultInstance();
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodRequest reqAddBloodBulk = 7;</code>
   */
  public farm.nurture.farm.service.proto.BulkAddBloodRequestOrBuilder getReqAddBloodBulkOrBuilder() {
    if (aRequestCase_ == 7) {
       return (farm.nurture.farm.service.proto.BulkAddBloodRequest) aRequest_;
    }
    return farm.nurture.farm.service.proto.BulkAddBloodRequest.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIndexBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, index_);
    }
    if (aRequestCase_ == 2) {
      output.writeMessage(2, (farm.nurture.farm.service.proto.FindPasswordRequest) aRequest_);
    }
    if (aRequestCase_ == 3) {
      output.writeMessage(3, (farm.nurture.farm.service.proto.AddUserRequest) aRequest_);
    }
    if (aRequestCase_ == 4) {
      output.writeMessage(4, (farm.nurture.farm.service.proto.BulkAddUserRequest) aRequest_);
    }
    if (aRequestCase_ == 5) {
      output.writeMessage(5, (farm.nurture.farm.service.proto.FindBloodRequest) aRequest_);
    }
    if (aRequestCase_ == 6) {
      output.writeMessage(6, (farm.nurture.farm.service.proto.AddBloodRequest) aRequest_);
    }
    if (aRequestCase_ == 7) {
      output.writeMessage(7, (farm.nurture.farm.service.proto.BulkAddBloodRequest) aRequest_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIndexBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, index_);
    }
    if (aRequestCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (farm.nurture.farm.service.proto.FindPasswordRequest) aRequest_);
    }
    if (aRequestCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (farm.nurture.farm.service.proto.AddUserRequest) aRequest_);
    }
    if (aRequestCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (farm.nurture.farm.service.proto.BulkAddUserRequest) aRequest_);
    }
    if (aRequestCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (farm.nurture.farm.service.proto.FindBloodRequest) aRequest_);
    }
    if (aRequestCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (farm.nurture.farm.service.proto.AddBloodRequest) aRequest_);
    }
    if (aRequestCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (farm.nurture.farm.service.proto.BulkAddBloodRequest) aRequest_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof farm.nurture.farm.service.proto.Request)) {
      return super.equals(obj);
    }
    farm.nurture.farm.service.proto.Request other = (farm.nurture.farm.service.proto.Request) obj;

    boolean result = true;
    result = result && getIndex()
        .equals(other.getIndex());
    result = result && getARequestCase().equals(
        other.getARequestCase());
    if (!result) return false;
    switch (aRequestCase_) {
      case 2:
        result = result && getReqFindPassword()
            .equals(other.getReqFindPassword());
        break;
      case 3:
        result = result && getReqAddUser()
            .equals(other.getReqAddUser());
        break;
      case 4:
        result = result && getReqAddUserBulk()
            .equals(other.getReqAddUserBulk());
        break;
      case 5:
        result = result && getReqFindBlood()
            .equals(other.getReqFindBlood());
        break;
      case 6:
        result = result && getReqAddBlood()
            .equals(other.getReqAddBlood());
        break;
      case 7:
        result = result && getReqAddBloodBulk()
            .equals(other.getReqAddBloodBulk());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getIndex().hashCode();
    switch (aRequestCase_) {
      case 2:
        hash = (37 * hash) + REQFINDPASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getReqFindPassword().hashCode();
        break;
      case 3:
        hash = (37 * hash) + REQADDUSER_FIELD_NUMBER;
        hash = (53 * hash) + getReqAddUser().hashCode();
        break;
      case 4:
        hash = (37 * hash) + REQADDUSERBULK_FIELD_NUMBER;
        hash = (53 * hash) + getReqAddUserBulk().hashCode();
        break;
      case 5:
        hash = (37 * hash) + REQFINDBLOOD_FIELD_NUMBER;
        hash = (53 * hash) + getReqFindBlood().hashCode();
        break;
      case 6:
        hash = (37 * hash) + REQADDBLOOD_FIELD_NUMBER;
        hash = (53 * hash) + getReqAddBlood().hashCode();
        break;
      case 7:
        hash = (37 * hash) + REQADDBLOODBULK_FIELD_NUMBER;
        hash = (53 * hash) + getReqAddBloodBulk().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static farm.nurture.farm.service.proto.Request parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static farm.nurture.farm.service.proto.Request parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.Request parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static farm.nurture.farm.service.proto.Request parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.Request parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static farm.nurture.farm.service.proto.Request parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.Request parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static farm.nurture.farm.service.proto.Request parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.Request parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static farm.nurture.farm.service.proto.Request parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.Request parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static farm.nurture.farm.service.proto.Request parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(farm.nurture.farm.service.proto.Request prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code farm.nurture.core.contracts.BloodBankSystemService.Request}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:farm.nurture.core.contracts.BloodBankSystemService.Request)
      farm.nurture.farm.service.proto.RequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              farm.nurture.farm.service.proto.Request.class, farm.nurture.farm.service.proto.Request.Builder.class);
    }

    // Construct using farm.nurture.farm.service.proto.Request.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      index_ = "";

      aRequestCase_ = 0;
      aRequest_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_Request_descriptor;
    }

    @java.lang.Override
    public farm.nurture.farm.service.proto.Request getDefaultInstanceForType() {
      return farm.nurture.farm.service.proto.Request.getDefaultInstance();
    }

    @java.lang.Override
    public farm.nurture.farm.service.proto.Request build() {
      farm.nurture.farm.service.proto.Request result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public farm.nurture.farm.service.proto.Request buildPartial() {
      farm.nurture.farm.service.proto.Request result = new farm.nurture.farm.service.proto.Request(this);
      result.index_ = index_;
      if (aRequestCase_ == 2) {
        if (reqFindPasswordBuilder_ == null) {
          result.aRequest_ = aRequest_;
        } else {
          result.aRequest_ = reqFindPasswordBuilder_.build();
        }
      }
      if (aRequestCase_ == 3) {
        if (reqAddUserBuilder_ == null) {
          result.aRequest_ = aRequest_;
        } else {
          result.aRequest_ = reqAddUserBuilder_.build();
        }
      }
      if (aRequestCase_ == 4) {
        if (reqAddUserBulkBuilder_ == null) {
          result.aRequest_ = aRequest_;
        } else {
          result.aRequest_ = reqAddUserBulkBuilder_.build();
        }
      }
      if (aRequestCase_ == 5) {
        if (reqFindBloodBuilder_ == null) {
          result.aRequest_ = aRequest_;
        } else {
          result.aRequest_ = reqFindBloodBuilder_.build();
        }
      }
      if (aRequestCase_ == 6) {
        if (reqAddBloodBuilder_ == null) {
          result.aRequest_ = aRequest_;
        } else {
          result.aRequest_ = reqAddBloodBuilder_.build();
        }
      }
      if (aRequestCase_ == 7) {
        if (reqAddBloodBulkBuilder_ == null) {
          result.aRequest_ = aRequest_;
        } else {
          result.aRequest_ = reqAddBloodBulkBuilder_.build();
        }
      }
      result.aRequestCase_ = aRequestCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof farm.nurture.farm.service.proto.Request) {
        return mergeFrom((farm.nurture.farm.service.proto.Request)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(farm.nurture.farm.service.proto.Request other) {
      if (other == farm.nurture.farm.service.proto.Request.getDefaultInstance()) return this;
      if (!other.getIndex().isEmpty()) {
        index_ = other.index_;
        onChanged();
      }
      switch (other.getARequestCase()) {
        case REQFINDPASSWORD: {
          mergeReqFindPassword(other.getReqFindPassword());
          break;
        }
        case REQADDUSER: {
          mergeReqAddUser(other.getReqAddUser());
          break;
        }
        case REQADDUSERBULK: {
          mergeReqAddUserBulk(other.getReqAddUserBulk());
          break;
        }
        case REQFINDBLOOD: {
          mergeReqFindBlood(other.getReqFindBlood());
          break;
        }
        case REQADDBLOOD: {
          mergeReqAddBlood(other.getReqAddBlood());
          break;
        }
        case REQADDBLOODBULK: {
          mergeReqAddBloodBulk(other.getReqAddBloodBulk());
          break;
        }
        case AREQUEST_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      farm.nurture.farm.service.proto.Request parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (farm.nurture.farm.service.proto.Request) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int aRequestCase_ = 0;
    private java.lang.Object aRequest_;
    public ARequestCase
        getARequestCase() {
      return ARequestCase.forNumber(
          aRequestCase_);
    }

    public Builder clearARequest() {
      aRequestCase_ = 0;
      aRequest_ = null;
      onChanged();
      return this;
    }


    private java.lang.Object index_ = "";
    /**
     * <code>string index = 1;</code>
     */
    public java.lang.String getIndex() {
      java.lang.Object ref = index_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        index_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string index = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIndexBytes() {
      java.lang.Object ref = index_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        index_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string index = 1;</code>
     */
    public Builder setIndex(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      index_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string index = 1;</code>
     */
    public Builder clearIndex() {
      
      index_ = getDefaultInstance().getIndex();
      onChanged();
      return this;
    }
    /**
     * <code>string index = 1;</code>
     */
    public Builder setIndexBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      index_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.FindPasswordRequest, farm.nurture.farm.service.proto.FindPasswordRequest.Builder, farm.nurture.farm.service.proto.FindPasswordRequestOrBuilder> reqFindPasswordBuilder_;
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordRequest reqFindPassword = 2;</code>
     */
    public boolean hasReqFindPassword() {
      return aRequestCase_ == 2;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordRequest reqFindPassword = 2;</code>
     */
    public farm.nurture.farm.service.proto.FindPasswordRequest getReqFindPassword() {
      if (reqFindPasswordBuilder_ == null) {
        if (aRequestCase_ == 2) {
          return (farm.nurture.farm.service.proto.FindPasswordRequest) aRequest_;
        }
        return farm.nurture.farm.service.proto.FindPasswordRequest.getDefaultInstance();
      } else {
        if (aRequestCase_ == 2) {
          return reqFindPasswordBuilder_.getMessage();
        }
        return farm.nurture.farm.service.proto.FindPasswordRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordRequest reqFindPassword = 2;</code>
     */
    public Builder setReqFindPassword(farm.nurture.farm.service.proto.FindPasswordRequest value) {
      if (reqFindPasswordBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        aRequest_ = value;
        onChanged();
      } else {
        reqFindPasswordBuilder_.setMessage(value);
      }
      aRequestCase_ = 2;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordRequest reqFindPassword = 2;</code>
     */
    public Builder setReqFindPassword(
        farm.nurture.farm.service.proto.FindPasswordRequest.Builder builderForValue) {
      if (reqFindPasswordBuilder_ == null) {
        aRequest_ = builderForValue.build();
        onChanged();
      } else {
        reqFindPasswordBuilder_.setMessage(builderForValue.build());
      }
      aRequestCase_ = 2;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordRequest reqFindPassword = 2;</code>
     */
    public Builder mergeReqFindPassword(farm.nurture.farm.service.proto.FindPasswordRequest value) {
      if (reqFindPasswordBuilder_ == null) {
        if (aRequestCase_ == 2 &&
            aRequest_ != farm.nurture.farm.service.proto.FindPasswordRequest.getDefaultInstance()) {
          aRequest_ = farm.nurture.farm.service.proto.FindPasswordRequest.newBuilder((farm.nurture.farm.service.proto.FindPasswordRequest) aRequest_)
              .mergeFrom(value).buildPartial();
        } else {
          aRequest_ = value;
        }
        onChanged();
      } else {
        if (aRequestCase_ == 2) {
          reqFindPasswordBuilder_.mergeFrom(value);
        }
        reqFindPasswordBuilder_.setMessage(value);
      }
      aRequestCase_ = 2;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordRequest reqFindPassword = 2;</code>
     */
    public Builder clearReqFindPassword() {
      if (reqFindPasswordBuilder_ == null) {
        if (aRequestCase_ == 2) {
          aRequestCase_ = 0;
          aRequest_ = null;
          onChanged();
        }
      } else {
        if (aRequestCase_ == 2) {
          aRequestCase_ = 0;
          aRequest_ = null;
        }
        reqFindPasswordBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordRequest reqFindPassword = 2;</code>
     */
    public farm.nurture.farm.service.proto.FindPasswordRequest.Builder getReqFindPasswordBuilder() {
      return getReqFindPasswordFieldBuilder().getBuilder();
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordRequest reqFindPassword = 2;</code>
     */
    public farm.nurture.farm.service.proto.FindPasswordRequestOrBuilder getReqFindPasswordOrBuilder() {
      if ((aRequestCase_ == 2) && (reqFindPasswordBuilder_ != null)) {
        return reqFindPasswordBuilder_.getMessageOrBuilder();
      } else {
        if (aRequestCase_ == 2) {
          return (farm.nurture.farm.service.proto.FindPasswordRequest) aRequest_;
        }
        return farm.nurture.farm.service.proto.FindPasswordRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordRequest reqFindPassword = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.FindPasswordRequest, farm.nurture.farm.service.proto.FindPasswordRequest.Builder, farm.nurture.farm.service.proto.FindPasswordRequestOrBuilder> 
        getReqFindPasswordFieldBuilder() {
      if (reqFindPasswordBuilder_ == null) {
        if (!(aRequestCase_ == 2)) {
          aRequest_ = farm.nurture.farm.service.proto.FindPasswordRequest.getDefaultInstance();
        }
        reqFindPasswordBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            farm.nurture.farm.service.proto.FindPasswordRequest, farm.nurture.farm.service.proto.FindPasswordRequest.Builder, farm.nurture.farm.service.proto.FindPasswordRequestOrBuilder>(
                (farm.nurture.farm.service.proto.FindPasswordRequest) aRequest_,
                getParentForChildren(),
                isClean());
        aRequest_ = null;
      }
      aRequestCase_ = 2;
      onChanged();;
      return reqFindPasswordBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.AddUserRequest, farm.nurture.farm.service.proto.AddUserRequest.Builder, farm.nurture.farm.service.proto.AddUserRequestOrBuilder> reqAddUserBuilder_;
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserRequest reqAddUser = 3;</code>
     */
    public boolean hasReqAddUser() {
      return aRequestCase_ == 3;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserRequest reqAddUser = 3;</code>
     */
    public farm.nurture.farm.service.proto.AddUserRequest getReqAddUser() {
      if (reqAddUserBuilder_ == null) {
        if (aRequestCase_ == 3) {
          return (farm.nurture.farm.service.proto.AddUserRequest) aRequest_;
        }
        return farm.nurture.farm.service.proto.AddUserRequest.getDefaultInstance();
      } else {
        if (aRequestCase_ == 3) {
          return reqAddUserBuilder_.getMessage();
        }
        return farm.nurture.farm.service.proto.AddUserRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserRequest reqAddUser = 3;</code>
     */
    public Builder setReqAddUser(farm.nurture.farm.service.proto.AddUserRequest value) {
      if (reqAddUserBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        aRequest_ = value;
        onChanged();
      } else {
        reqAddUserBuilder_.setMessage(value);
      }
      aRequestCase_ = 3;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserRequest reqAddUser = 3;</code>
     */
    public Builder setReqAddUser(
        farm.nurture.farm.service.proto.AddUserRequest.Builder builderForValue) {
      if (reqAddUserBuilder_ == null) {
        aRequest_ = builderForValue.build();
        onChanged();
      } else {
        reqAddUserBuilder_.setMessage(builderForValue.build());
      }
      aRequestCase_ = 3;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserRequest reqAddUser = 3;</code>
     */
    public Builder mergeReqAddUser(farm.nurture.farm.service.proto.AddUserRequest value) {
      if (reqAddUserBuilder_ == null) {
        if (aRequestCase_ == 3 &&
            aRequest_ != farm.nurture.farm.service.proto.AddUserRequest.getDefaultInstance()) {
          aRequest_ = farm.nurture.farm.service.proto.AddUserRequest.newBuilder((farm.nurture.farm.service.proto.AddUserRequest) aRequest_)
              .mergeFrom(value).buildPartial();
        } else {
          aRequest_ = value;
        }
        onChanged();
      } else {
        if (aRequestCase_ == 3) {
          reqAddUserBuilder_.mergeFrom(value);
        }
        reqAddUserBuilder_.setMessage(value);
      }
      aRequestCase_ = 3;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserRequest reqAddUser = 3;</code>
     */
    public Builder clearReqAddUser() {
      if (reqAddUserBuilder_ == null) {
        if (aRequestCase_ == 3) {
          aRequestCase_ = 0;
          aRequest_ = null;
          onChanged();
        }
      } else {
        if (aRequestCase_ == 3) {
          aRequestCase_ = 0;
          aRequest_ = null;
        }
        reqAddUserBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserRequest reqAddUser = 3;</code>
     */
    public farm.nurture.farm.service.proto.AddUserRequest.Builder getReqAddUserBuilder() {
      return getReqAddUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserRequest reqAddUser = 3;</code>
     */
    public farm.nurture.farm.service.proto.AddUserRequestOrBuilder getReqAddUserOrBuilder() {
      if ((aRequestCase_ == 3) && (reqAddUserBuilder_ != null)) {
        return reqAddUserBuilder_.getMessageOrBuilder();
      } else {
        if (aRequestCase_ == 3) {
          return (farm.nurture.farm.service.proto.AddUserRequest) aRequest_;
        }
        return farm.nurture.farm.service.proto.AddUserRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserRequest reqAddUser = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.AddUserRequest, farm.nurture.farm.service.proto.AddUserRequest.Builder, farm.nurture.farm.service.proto.AddUserRequestOrBuilder> 
        getReqAddUserFieldBuilder() {
      if (reqAddUserBuilder_ == null) {
        if (!(aRequestCase_ == 3)) {
          aRequest_ = farm.nurture.farm.service.proto.AddUserRequest.getDefaultInstance();
        }
        reqAddUserBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            farm.nurture.farm.service.proto.AddUserRequest, farm.nurture.farm.service.proto.AddUserRequest.Builder, farm.nurture.farm.service.proto.AddUserRequestOrBuilder>(
                (farm.nurture.farm.service.proto.AddUserRequest) aRequest_,
                getParentForChildren(),
                isClean());
        aRequest_ = null;
      }
      aRequestCase_ = 3;
      onChanged();;
      return reqAddUserBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.BulkAddUserRequest, farm.nurture.farm.service.proto.BulkAddUserRequest.Builder, farm.nurture.farm.service.proto.BulkAddUserRequestOrBuilder> reqAddUserBulkBuilder_;
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserRequest reqAddUserBulk = 4;</code>
     */
    public boolean hasReqAddUserBulk() {
      return aRequestCase_ == 4;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserRequest reqAddUserBulk = 4;</code>
     */
    public farm.nurture.farm.service.proto.BulkAddUserRequest getReqAddUserBulk() {
      if (reqAddUserBulkBuilder_ == null) {
        if (aRequestCase_ == 4) {
          return (farm.nurture.farm.service.proto.BulkAddUserRequest) aRequest_;
        }
        return farm.nurture.farm.service.proto.BulkAddUserRequest.getDefaultInstance();
      } else {
        if (aRequestCase_ == 4) {
          return reqAddUserBulkBuilder_.getMessage();
        }
        return farm.nurture.farm.service.proto.BulkAddUserRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserRequest reqAddUserBulk = 4;</code>
     */
    public Builder setReqAddUserBulk(farm.nurture.farm.service.proto.BulkAddUserRequest value) {
      if (reqAddUserBulkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        aRequest_ = value;
        onChanged();
      } else {
        reqAddUserBulkBuilder_.setMessage(value);
      }
      aRequestCase_ = 4;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserRequest reqAddUserBulk = 4;</code>
     */
    public Builder setReqAddUserBulk(
        farm.nurture.farm.service.proto.BulkAddUserRequest.Builder builderForValue) {
      if (reqAddUserBulkBuilder_ == null) {
        aRequest_ = builderForValue.build();
        onChanged();
      } else {
        reqAddUserBulkBuilder_.setMessage(builderForValue.build());
      }
      aRequestCase_ = 4;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserRequest reqAddUserBulk = 4;</code>
     */
    public Builder mergeReqAddUserBulk(farm.nurture.farm.service.proto.BulkAddUserRequest value) {
      if (reqAddUserBulkBuilder_ == null) {
        if (aRequestCase_ == 4 &&
            aRequest_ != farm.nurture.farm.service.proto.BulkAddUserRequest.getDefaultInstance()) {
          aRequest_ = farm.nurture.farm.service.proto.BulkAddUserRequest.newBuilder((farm.nurture.farm.service.proto.BulkAddUserRequest) aRequest_)
              .mergeFrom(value).buildPartial();
        } else {
          aRequest_ = value;
        }
        onChanged();
      } else {
        if (aRequestCase_ == 4) {
          reqAddUserBulkBuilder_.mergeFrom(value);
        }
        reqAddUserBulkBuilder_.setMessage(value);
      }
      aRequestCase_ = 4;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserRequest reqAddUserBulk = 4;</code>
     */
    public Builder clearReqAddUserBulk() {
      if (reqAddUserBulkBuilder_ == null) {
        if (aRequestCase_ == 4) {
          aRequestCase_ = 0;
          aRequest_ = null;
          onChanged();
        }
      } else {
        if (aRequestCase_ == 4) {
          aRequestCase_ = 0;
          aRequest_ = null;
        }
        reqAddUserBulkBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserRequest reqAddUserBulk = 4;</code>
     */
    public farm.nurture.farm.service.proto.BulkAddUserRequest.Builder getReqAddUserBulkBuilder() {
      return getReqAddUserBulkFieldBuilder().getBuilder();
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserRequest reqAddUserBulk = 4;</code>
     */
    public farm.nurture.farm.service.proto.BulkAddUserRequestOrBuilder getReqAddUserBulkOrBuilder() {
      if ((aRequestCase_ == 4) && (reqAddUserBulkBuilder_ != null)) {
        return reqAddUserBulkBuilder_.getMessageOrBuilder();
      } else {
        if (aRequestCase_ == 4) {
          return (farm.nurture.farm.service.proto.BulkAddUserRequest) aRequest_;
        }
        return farm.nurture.farm.service.proto.BulkAddUserRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserRequest reqAddUserBulk = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.BulkAddUserRequest, farm.nurture.farm.service.proto.BulkAddUserRequest.Builder, farm.nurture.farm.service.proto.BulkAddUserRequestOrBuilder> 
        getReqAddUserBulkFieldBuilder() {
      if (reqAddUserBulkBuilder_ == null) {
        if (!(aRequestCase_ == 4)) {
          aRequest_ = farm.nurture.farm.service.proto.BulkAddUserRequest.getDefaultInstance();
        }
        reqAddUserBulkBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            farm.nurture.farm.service.proto.BulkAddUserRequest, farm.nurture.farm.service.proto.BulkAddUserRequest.Builder, farm.nurture.farm.service.proto.BulkAddUserRequestOrBuilder>(
                (farm.nurture.farm.service.proto.BulkAddUserRequest) aRequest_,
                getParentForChildren(),
                isClean());
        aRequest_ = null;
      }
      aRequestCase_ = 4;
      onChanged();;
      return reqAddUserBulkBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.FindBloodRequest, farm.nurture.farm.service.proto.FindBloodRequest.Builder, farm.nurture.farm.service.proto.FindBloodRequestOrBuilder> reqFindBloodBuilder_;
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodRequest reqFindBlood = 5;</code>
     */
    public boolean hasReqFindBlood() {
      return aRequestCase_ == 5;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodRequest reqFindBlood = 5;</code>
     */
    public farm.nurture.farm.service.proto.FindBloodRequest getReqFindBlood() {
      if (reqFindBloodBuilder_ == null) {
        if (aRequestCase_ == 5) {
          return (farm.nurture.farm.service.proto.FindBloodRequest) aRequest_;
        }
        return farm.nurture.farm.service.proto.FindBloodRequest.getDefaultInstance();
      } else {
        if (aRequestCase_ == 5) {
          return reqFindBloodBuilder_.getMessage();
        }
        return farm.nurture.farm.service.proto.FindBloodRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodRequest reqFindBlood = 5;</code>
     */
    public Builder setReqFindBlood(farm.nurture.farm.service.proto.FindBloodRequest value) {
      if (reqFindBloodBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        aRequest_ = value;
        onChanged();
      } else {
        reqFindBloodBuilder_.setMessage(value);
      }
      aRequestCase_ = 5;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodRequest reqFindBlood = 5;</code>
     */
    public Builder setReqFindBlood(
        farm.nurture.farm.service.proto.FindBloodRequest.Builder builderForValue) {
      if (reqFindBloodBuilder_ == null) {
        aRequest_ = builderForValue.build();
        onChanged();
      } else {
        reqFindBloodBuilder_.setMessage(builderForValue.build());
      }
      aRequestCase_ = 5;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodRequest reqFindBlood = 5;</code>
     */
    public Builder mergeReqFindBlood(farm.nurture.farm.service.proto.FindBloodRequest value) {
      if (reqFindBloodBuilder_ == null) {
        if (aRequestCase_ == 5 &&
            aRequest_ != farm.nurture.farm.service.proto.FindBloodRequest.getDefaultInstance()) {
          aRequest_ = farm.nurture.farm.service.proto.FindBloodRequest.newBuilder((farm.nurture.farm.service.proto.FindBloodRequest) aRequest_)
              .mergeFrom(value).buildPartial();
        } else {
          aRequest_ = value;
        }
        onChanged();
      } else {
        if (aRequestCase_ == 5) {
          reqFindBloodBuilder_.mergeFrom(value);
        }
        reqFindBloodBuilder_.setMessage(value);
      }
      aRequestCase_ = 5;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodRequest reqFindBlood = 5;</code>
     */
    public Builder clearReqFindBlood() {
      if (reqFindBloodBuilder_ == null) {
        if (aRequestCase_ == 5) {
          aRequestCase_ = 0;
          aRequest_ = null;
          onChanged();
        }
      } else {
        if (aRequestCase_ == 5) {
          aRequestCase_ = 0;
          aRequest_ = null;
        }
        reqFindBloodBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodRequest reqFindBlood = 5;</code>
     */
    public farm.nurture.farm.service.proto.FindBloodRequest.Builder getReqFindBloodBuilder() {
      return getReqFindBloodFieldBuilder().getBuilder();
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodRequest reqFindBlood = 5;</code>
     */
    public farm.nurture.farm.service.proto.FindBloodRequestOrBuilder getReqFindBloodOrBuilder() {
      if ((aRequestCase_ == 5) && (reqFindBloodBuilder_ != null)) {
        return reqFindBloodBuilder_.getMessageOrBuilder();
      } else {
        if (aRequestCase_ == 5) {
          return (farm.nurture.farm.service.proto.FindBloodRequest) aRequest_;
        }
        return farm.nurture.farm.service.proto.FindBloodRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodRequest reqFindBlood = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.FindBloodRequest, farm.nurture.farm.service.proto.FindBloodRequest.Builder, farm.nurture.farm.service.proto.FindBloodRequestOrBuilder> 
        getReqFindBloodFieldBuilder() {
      if (reqFindBloodBuilder_ == null) {
        if (!(aRequestCase_ == 5)) {
          aRequest_ = farm.nurture.farm.service.proto.FindBloodRequest.getDefaultInstance();
        }
        reqFindBloodBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            farm.nurture.farm.service.proto.FindBloodRequest, farm.nurture.farm.service.proto.FindBloodRequest.Builder, farm.nurture.farm.service.proto.FindBloodRequestOrBuilder>(
                (farm.nurture.farm.service.proto.FindBloodRequest) aRequest_,
                getParentForChildren(),
                isClean());
        aRequest_ = null;
      }
      aRequestCase_ = 5;
      onChanged();;
      return reqFindBloodBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.AddBloodRequest, farm.nurture.farm.service.proto.AddBloodRequest.Builder, farm.nurture.farm.service.proto.AddBloodRequestOrBuilder> reqAddBloodBuilder_;
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodRequest reqAddBlood = 6;</code>
     */
    public boolean hasReqAddBlood() {
      return aRequestCase_ == 6;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodRequest reqAddBlood = 6;</code>
     */
    public farm.nurture.farm.service.proto.AddBloodRequest getReqAddBlood() {
      if (reqAddBloodBuilder_ == null) {
        if (aRequestCase_ == 6) {
          return (farm.nurture.farm.service.proto.AddBloodRequest) aRequest_;
        }
        return farm.nurture.farm.service.proto.AddBloodRequest.getDefaultInstance();
      } else {
        if (aRequestCase_ == 6) {
          return reqAddBloodBuilder_.getMessage();
        }
        return farm.nurture.farm.service.proto.AddBloodRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodRequest reqAddBlood = 6;</code>
     */
    public Builder setReqAddBlood(farm.nurture.farm.service.proto.AddBloodRequest value) {
      if (reqAddBloodBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        aRequest_ = value;
        onChanged();
      } else {
        reqAddBloodBuilder_.setMessage(value);
      }
      aRequestCase_ = 6;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodRequest reqAddBlood = 6;</code>
     */
    public Builder setReqAddBlood(
        farm.nurture.farm.service.proto.AddBloodRequest.Builder builderForValue) {
      if (reqAddBloodBuilder_ == null) {
        aRequest_ = builderForValue.build();
        onChanged();
      } else {
        reqAddBloodBuilder_.setMessage(builderForValue.build());
      }
      aRequestCase_ = 6;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodRequest reqAddBlood = 6;</code>
     */
    public Builder mergeReqAddBlood(farm.nurture.farm.service.proto.AddBloodRequest value) {
      if (reqAddBloodBuilder_ == null) {
        if (aRequestCase_ == 6 &&
            aRequest_ != farm.nurture.farm.service.proto.AddBloodRequest.getDefaultInstance()) {
          aRequest_ = farm.nurture.farm.service.proto.AddBloodRequest.newBuilder((farm.nurture.farm.service.proto.AddBloodRequest) aRequest_)
              .mergeFrom(value).buildPartial();
        } else {
          aRequest_ = value;
        }
        onChanged();
      } else {
        if (aRequestCase_ == 6) {
          reqAddBloodBuilder_.mergeFrom(value);
        }
        reqAddBloodBuilder_.setMessage(value);
      }
      aRequestCase_ = 6;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodRequest reqAddBlood = 6;</code>
     */
    public Builder clearReqAddBlood() {
      if (reqAddBloodBuilder_ == null) {
        if (aRequestCase_ == 6) {
          aRequestCase_ = 0;
          aRequest_ = null;
          onChanged();
        }
      } else {
        if (aRequestCase_ == 6) {
          aRequestCase_ = 0;
          aRequest_ = null;
        }
        reqAddBloodBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodRequest reqAddBlood = 6;</code>
     */
    public farm.nurture.farm.service.proto.AddBloodRequest.Builder getReqAddBloodBuilder() {
      return getReqAddBloodFieldBuilder().getBuilder();
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodRequest reqAddBlood = 6;</code>
     */
    public farm.nurture.farm.service.proto.AddBloodRequestOrBuilder getReqAddBloodOrBuilder() {
      if ((aRequestCase_ == 6) && (reqAddBloodBuilder_ != null)) {
        return reqAddBloodBuilder_.getMessageOrBuilder();
      } else {
        if (aRequestCase_ == 6) {
          return (farm.nurture.farm.service.proto.AddBloodRequest) aRequest_;
        }
        return farm.nurture.farm.service.proto.AddBloodRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodRequest reqAddBlood = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.AddBloodRequest, farm.nurture.farm.service.proto.AddBloodRequest.Builder, farm.nurture.farm.service.proto.AddBloodRequestOrBuilder> 
        getReqAddBloodFieldBuilder() {
      if (reqAddBloodBuilder_ == null) {
        if (!(aRequestCase_ == 6)) {
          aRequest_ = farm.nurture.farm.service.proto.AddBloodRequest.getDefaultInstance();
        }
        reqAddBloodBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            farm.nurture.farm.service.proto.AddBloodRequest, farm.nurture.farm.service.proto.AddBloodRequest.Builder, farm.nurture.farm.service.proto.AddBloodRequestOrBuilder>(
                (farm.nurture.farm.service.proto.AddBloodRequest) aRequest_,
                getParentForChildren(),
                isClean());
        aRequest_ = null;
      }
      aRequestCase_ = 6;
      onChanged();;
      return reqAddBloodBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.BulkAddBloodRequest, farm.nurture.farm.service.proto.BulkAddBloodRequest.Builder, farm.nurture.farm.service.proto.BulkAddBloodRequestOrBuilder> reqAddBloodBulkBuilder_;
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodRequest reqAddBloodBulk = 7;</code>
     */
    public boolean hasReqAddBloodBulk() {
      return aRequestCase_ == 7;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodRequest reqAddBloodBulk = 7;</code>
     */
    public farm.nurture.farm.service.proto.BulkAddBloodRequest getReqAddBloodBulk() {
      if (reqAddBloodBulkBuilder_ == null) {
        if (aRequestCase_ == 7) {
          return (farm.nurture.farm.service.proto.BulkAddBloodRequest) aRequest_;
        }
        return farm.nurture.farm.service.proto.BulkAddBloodRequest.getDefaultInstance();
      } else {
        if (aRequestCase_ == 7) {
          return reqAddBloodBulkBuilder_.getMessage();
        }
        return farm.nurture.farm.service.proto.BulkAddBloodRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodRequest reqAddBloodBulk = 7;</code>
     */
    public Builder setReqAddBloodBulk(farm.nurture.farm.service.proto.BulkAddBloodRequest value) {
      if (reqAddBloodBulkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        aRequest_ = value;
        onChanged();
      } else {
        reqAddBloodBulkBuilder_.setMessage(value);
      }
      aRequestCase_ = 7;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodRequest reqAddBloodBulk = 7;</code>
     */
    public Builder setReqAddBloodBulk(
        farm.nurture.farm.service.proto.BulkAddBloodRequest.Builder builderForValue) {
      if (reqAddBloodBulkBuilder_ == null) {
        aRequest_ = builderForValue.build();
        onChanged();
      } else {
        reqAddBloodBulkBuilder_.setMessage(builderForValue.build());
      }
      aRequestCase_ = 7;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodRequest reqAddBloodBulk = 7;</code>
     */
    public Builder mergeReqAddBloodBulk(farm.nurture.farm.service.proto.BulkAddBloodRequest value) {
      if (reqAddBloodBulkBuilder_ == null) {
        if (aRequestCase_ == 7 &&
            aRequest_ != farm.nurture.farm.service.proto.BulkAddBloodRequest.getDefaultInstance()) {
          aRequest_ = farm.nurture.farm.service.proto.BulkAddBloodRequest.newBuilder((farm.nurture.farm.service.proto.BulkAddBloodRequest) aRequest_)
              .mergeFrom(value).buildPartial();
        } else {
          aRequest_ = value;
        }
        onChanged();
      } else {
        if (aRequestCase_ == 7) {
          reqAddBloodBulkBuilder_.mergeFrom(value);
        }
        reqAddBloodBulkBuilder_.setMessage(value);
      }
      aRequestCase_ = 7;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodRequest reqAddBloodBulk = 7;</code>
     */
    public Builder clearReqAddBloodBulk() {
      if (reqAddBloodBulkBuilder_ == null) {
        if (aRequestCase_ == 7) {
          aRequestCase_ = 0;
          aRequest_ = null;
          onChanged();
        }
      } else {
        if (aRequestCase_ == 7) {
          aRequestCase_ = 0;
          aRequest_ = null;
        }
        reqAddBloodBulkBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodRequest reqAddBloodBulk = 7;</code>
     */
    public farm.nurture.farm.service.proto.BulkAddBloodRequest.Builder getReqAddBloodBulkBuilder() {
      return getReqAddBloodBulkFieldBuilder().getBuilder();
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodRequest reqAddBloodBulk = 7;</code>
     */
    public farm.nurture.farm.service.proto.BulkAddBloodRequestOrBuilder getReqAddBloodBulkOrBuilder() {
      if ((aRequestCase_ == 7) && (reqAddBloodBulkBuilder_ != null)) {
        return reqAddBloodBulkBuilder_.getMessageOrBuilder();
      } else {
        if (aRequestCase_ == 7) {
          return (farm.nurture.farm.service.proto.BulkAddBloodRequest) aRequest_;
        }
        return farm.nurture.farm.service.proto.BulkAddBloodRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodRequest reqAddBloodBulk = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.BulkAddBloodRequest, farm.nurture.farm.service.proto.BulkAddBloodRequest.Builder, farm.nurture.farm.service.proto.BulkAddBloodRequestOrBuilder> 
        getReqAddBloodBulkFieldBuilder() {
      if (reqAddBloodBulkBuilder_ == null) {
        if (!(aRequestCase_ == 7)) {
          aRequest_ = farm.nurture.farm.service.proto.BulkAddBloodRequest.getDefaultInstance();
        }
        reqAddBloodBulkBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            farm.nurture.farm.service.proto.BulkAddBloodRequest, farm.nurture.farm.service.proto.BulkAddBloodRequest.Builder, farm.nurture.farm.service.proto.BulkAddBloodRequestOrBuilder>(
                (farm.nurture.farm.service.proto.BulkAddBloodRequest) aRequest_,
                getParentForChildren(),
                isClean());
        aRequest_ = null;
      }
      aRequestCase_ = 7;
      onChanged();;
      return reqAddBloodBulkBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:farm.nurture.core.contracts.BloodBankSystemService.Request)
  }

  // @@protoc_insertion_point(class_scope:farm.nurture.core.contracts.BloodBankSystemService.Request)
  private static final farm.nurture.farm.service.proto.Request DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new farm.nurture.farm.service.proto.Request();
  }

  public static farm.nurture.farm.service.proto.Request getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Request>
      PARSER = new com.google.protobuf.AbstractParser<Request>() {
    @java.lang.Override
    public Request parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Request(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Request> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Request> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public farm.nurture.farm.service.proto.Request getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

