// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blood_bank_system_service.proto

package farm.nurture.farm.service.proto;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:farm.nurture.core.contracts.BloodBankSystemService.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string index = 1;</code>
   */
  java.lang.String getIndex();
  /**
   * <code>string index = 1;</code>
   */
  com.google.protobuf.ByteString
      getIndexBytes();

  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 2;</code>
   */
  boolean hasStatus();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 2;</code>
   */
  farm.nurture.farm.service.proto.Status getStatus();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 2;</code>
   */
  farm.nurture.farm.service.proto.StatusOrBuilder getStatusOrBuilder();

  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordResponse resFindPassword = 3;</code>
   */
  boolean hasResFindPassword();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordResponse resFindPassword = 3;</code>
   */
  farm.nurture.farm.service.proto.FindPasswordResponse getResFindPassword();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordResponse resFindPassword = 3;</code>
   */
  farm.nurture.farm.service.proto.FindPasswordResponseOrBuilder getResFindPasswordOrBuilder();

  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse resAddUser = 4;</code>
   */
  boolean hasResAddUser();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse resAddUser = 4;</code>
   */
  farm.nurture.farm.service.proto.AddUserResponse getResAddUser();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse resAddUser = 4;</code>
   */
  farm.nurture.farm.service.proto.AddUserResponseOrBuilder getResAddUserOrBuilder();

  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserResponse resAddUserBulk = 5;</code>
   */
  boolean hasResAddUserBulk();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserResponse resAddUserBulk = 5;</code>
   */
  farm.nurture.farm.service.proto.BulkAddUserResponse getResAddUserBulk();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserResponse resAddUserBulk = 5;</code>
   */
  farm.nurture.farm.service.proto.BulkAddUserResponseOrBuilder getResAddUserBulkOrBuilder();

  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodResponse resFindBlood = 6;</code>
   */
  boolean hasResFindBlood();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodResponse resFindBlood = 6;</code>
   */
  farm.nurture.farm.service.proto.FindBloodResponse getResFindBlood();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodResponse resFindBlood = 6;</code>
   */
  farm.nurture.farm.service.proto.FindBloodResponseOrBuilder getResFindBloodOrBuilder();

  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodResponse resAddBlood = 7;</code>
   */
  boolean hasResAddBlood();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodResponse resAddBlood = 7;</code>
   */
  farm.nurture.farm.service.proto.AddBloodResponse getResAddBlood();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodResponse resAddBlood = 7;</code>
   */
  farm.nurture.farm.service.proto.AddBloodResponseOrBuilder getResAddBloodOrBuilder();

  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodResponse resAddBloodBulk = 8;</code>
   */
  boolean hasResAddBloodBulk();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodResponse resAddBloodBulk = 8;</code>
   */
  farm.nurture.farm.service.proto.BulkAddBloodResponse getResAddBloodBulk();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodResponse resAddBloodBulk = 8;</code>
   */
  farm.nurture.farm.service.proto.BulkAddBloodResponseOrBuilder getResAddBloodBulkOrBuilder();

  public farm.nurture.farm.service.proto.Response.AResponseCase getAResponseCase();
}
