// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blood_bank_system_service.proto

package farm.nurture.farm.service.proto;

/**
 * Protobuf type {@code farm.nurture.core.contracts.BloodBankSystemService.Response}
 */
public  final class Response extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:farm.nurture.core.contracts.BloodBankSystemService.Response)
    ResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Response.newBuilder() to construct.
  private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Response() {
    index_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Response(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            index_ = s;
            break;
          }
          case 18: {
            farm.nurture.farm.service.proto.Status.Builder subBuilder = null;
            if (status_ != null) {
              subBuilder = status_.toBuilder();
            }
            status_ = input.readMessage(farm.nurture.farm.service.proto.Status.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(status_);
              status_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            farm.nurture.farm.service.proto.FindPasswordResponse.Builder subBuilder = null;
            if (aResponseCase_ == 3) {
              subBuilder = ((farm.nurture.farm.service.proto.FindPasswordResponse) aResponse_).toBuilder();
            }
            aResponse_ =
                input.readMessage(farm.nurture.farm.service.proto.FindPasswordResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((farm.nurture.farm.service.proto.FindPasswordResponse) aResponse_);
              aResponse_ = subBuilder.buildPartial();
            }
            aResponseCase_ = 3;
            break;
          }
          case 34: {
            farm.nurture.farm.service.proto.AddUserResponse.Builder subBuilder = null;
            if (aResponseCase_ == 4) {
              subBuilder = ((farm.nurture.farm.service.proto.AddUserResponse) aResponse_).toBuilder();
            }
            aResponse_ =
                input.readMessage(farm.nurture.farm.service.proto.AddUserResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((farm.nurture.farm.service.proto.AddUserResponse) aResponse_);
              aResponse_ = subBuilder.buildPartial();
            }
            aResponseCase_ = 4;
            break;
          }
          case 42: {
            farm.nurture.farm.service.proto.BulkAddUserResponse.Builder subBuilder = null;
            if (aResponseCase_ == 5) {
              subBuilder = ((farm.nurture.farm.service.proto.BulkAddUserResponse) aResponse_).toBuilder();
            }
            aResponse_ =
                input.readMessage(farm.nurture.farm.service.proto.BulkAddUserResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((farm.nurture.farm.service.proto.BulkAddUserResponse) aResponse_);
              aResponse_ = subBuilder.buildPartial();
            }
            aResponseCase_ = 5;
            break;
          }
          case 50: {
            farm.nurture.farm.service.proto.FindBloodResponse.Builder subBuilder = null;
            if (aResponseCase_ == 6) {
              subBuilder = ((farm.nurture.farm.service.proto.FindBloodResponse) aResponse_).toBuilder();
            }
            aResponse_ =
                input.readMessage(farm.nurture.farm.service.proto.FindBloodResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((farm.nurture.farm.service.proto.FindBloodResponse) aResponse_);
              aResponse_ = subBuilder.buildPartial();
            }
            aResponseCase_ = 6;
            break;
          }
          case 58: {
            farm.nurture.farm.service.proto.AddBloodResponse.Builder subBuilder = null;
            if (aResponseCase_ == 7) {
              subBuilder = ((farm.nurture.farm.service.proto.AddBloodResponse) aResponse_).toBuilder();
            }
            aResponse_ =
                input.readMessage(farm.nurture.farm.service.proto.AddBloodResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((farm.nurture.farm.service.proto.AddBloodResponse) aResponse_);
              aResponse_ = subBuilder.buildPartial();
            }
            aResponseCase_ = 7;
            break;
          }
          case 66: {
            farm.nurture.farm.service.proto.BulkAddBloodResponse.Builder subBuilder = null;
            if (aResponseCase_ == 8) {
              subBuilder = ((farm.nurture.farm.service.proto.BulkAddBloodResponse) aResponse_).toBuilder();
            }
            aResponse_ =
                input.readMessage(farm.nurture.farm.service.proto.BulkAddBloodResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((farm.nurture.farm.service.proto.BulkAddBloodResponse) aResponse_);
              aResponse_ = subBuilder.buildPartial();
            }
            aResponseCase_ = 8;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_Response_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_Response_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            farm.nurture.farm.service.proto.Response.class, farm.nurture.farm.service.proto.Response.Builder.class);
  }

  private int aResponseCase_ = 0;
  private java.lang.Object aResponse_;
  public enum AResponseCase
      implements com.google.protobuf.Internal.EnumLite {
    RESFINDPASSWORD(3),
    RESADDUSER(4),
    RESADDUSERBULK(5),
    RESFINDBLOOD(6),
    RESADDBLOOD(7),
    RESADDBLOODBULK(8),
    ARESPONSE_NOT_SET(0);
    private final int value;
    private AResponseCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AResponseCase valueOf(int value) {
      return forNumber(value);
    }

    public static AResponseCase forNumber(int value) {
      switch (value) {
        case 3: return RESFINDPASSWORD;
        case 4: return RESADDUSER;
        case 5: return RESADDUSERBULK;
        case 6: return RESFINDBLOOD;
        case 7: return RESADDBLOOD;
        case 8: return RESADDBLOODBULK;
        case 0: return ARESPONSE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public AResponseCase
  getAResponseCase() {
    return AResponseCase.forNumber(
        aResponseCase_);
  }

  public static final int INDEX_FIELD_NUMBER = 1;
  private volatile java.lang.Object index_;
  /**
   * <code>string index = 1;</code>
   */
  public java.lang.String getIndex() {
    java.lang.Object ref = index_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      index_ = s;
      return s;
    }
  }
  /**
   * <code>string index = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIndexBytes() {
    java.lang.Object ref = index_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      index_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private farm.nurture.farm.service.proto.Status status_;
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 2;</code>
   */
  public boolean hasStatus() {
    return status_ != null;
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 2;</code>
   */
  public farm.nurture.farm.service.proto.Status getStatus() {
    return status_ == null ? farm.nurture.farm.service.proto.Status.getDefaultInstance() : status_;
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 2;</code>
   */
  public farm.nurture.farm.service.proto.StatusOrBuilder getStatusOrBuilder() {
    return getStatus();
  }

  public static final int RESFINDPASSWORD_FIELD_NUMBER = 3;
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordResponse resFindPassword = 3;</code>
   */
  public boolean hasResFindPassword() {
    return aResponseCase_ == 3;
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordResponse resFindPassword = 3;</code>
   */
  public farm.nurture.farm.service.proto.FindPasswordResponse getResFindPassword() {
    if (aResponseCase_ == 3) {
       return (farm.nurture.farm.service.proto.FindPasswordResponse) aResponse_;
    }
    return farm.nurture.farm.service.proto.FindPasswordResponse.getDefaultInstance();
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordResponse resFindPassword = 3;</code>
   */
  public farm.nurture.farm.service.proto.FindPasswordResponseOrBuilder getResFindPasswordOrBuilder() {
    if (aResponseCase_ == 3) {
       return (farm.nurture.farm.service.proto.FindPasswordResponse) aResponse_;
    }
    return farm.nurture.farm.service.proto.FindPasswordResponse.getDefaultInstance();
  }

  public static final int RESADDUSER_FIELD_NUMBER = 4;
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse resAddUser = 4;</code>
   */
  public boolean hasResAddUser() {
    return aResponseCase_ == 4;
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse resAddUser = 4;</code>
   */
  public farm.nurture.farm.service.proto.AddUserResponse getResAddUser() {
    if (aResponseCase_ == 4) {
       return (farm.nurture.farm.service.proto.AddUserResponse) aResponse_;
    }
    return farm.nurture.farm.service.proto.AddUserResponse.getDefaultInstance();
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse resAddUser = 4;</code>
   */
  public farm.nurture.farm.service.proto.AddUserResponseOrBuilder getResAddUserOrBuilder() {
    if (aResponseCase_ == 4) {
       return (farm.nurture.farm.service.proto.AddUserResponse) aResponse_;
    }
    return farm.nurture.farm.service.proto.AddUserResponse.getDefaultInstance();
  }

  public static final int RESADDUSERBULK_FIELD_NUMBER = 5;
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserResponse resAddUserBulk = 5;</code>
   */
  public boolean hasResAddUserBulk() {
    return aResponseCase_ == 5;
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserResponse resAddUserBulk = 5;</code>
   */
  public farm.nurture.farm.service.proto.BulkAddUserResponse getResAddUserBulk() {
    if (aResponseCase_ == 5) {
       return (farm.nurture.farm.service.proto.BulkAddUserResponse) aResponse_;
    }
    return farm.nurture.farm.service.proto.BulkAddUserResponse.getDefaultInstance();
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserResponse resAddUserBulk = 5;</code>
   */
  public farm.nurture.farm.service.proto.BulkAddUserResponseOrBuilder getResAddUserBulkOrBuilder() {
    if (aResponseCase_ == 5) {
       return (farm.nurture.farm.service.proto.BulkAddUserResponse) aResponse_;
    }
    return farm.nurture.farm.service.proto.BulkAddUserResponse.getDefaultInstance();
  }

  public static final int RESFINDBLOOD_FIELD_NUMBER = 6;
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodResponse resFindBlood = 6;</code>
   */
  public boolean hasResFindBlood() {
    return aResponseCase_ == 6;
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodResponse resFindBlood = 6;</code>
   */
  public farm.nurture.farm.service.proto.FindBloodResponse getResFindBlood() {
    if (aResponseCase_ == 6) {
       return (farm.nurture.farm.service.proto.FindBloodResponse) aResponse_;
    }
    return farm.nurture.farm.service.proto.FindBloodResponse.getDefaultInstance();
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodResponse resFindBlood = 6;</code>
   */
  public farm.nurture.farm.service.proto.FindBloodResponseOrBuilder getResFindBloodOrBuilder() {
    if (aResponseCase_ == 6) {
       return (farm.nurture.farm.service.proto.FindBloodResponse) aResponse_;
    }
    return farm.nurture.farm.service.proto.FindBloodResponse.getDefaultInstance();
  }

  public static final int RESADDBLOOD_FIELD_NUMBER = 7;
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodResponse resAddBlood = 7;</code>
   */
  public boolean hasResAddBlood() {
    return aResponseCase_ == 7;
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodResponse resAddBlood = 7;</code>
   */
  public farm.nurture.farm.service.proto.AddBloodResponse getResAddBlood() {
    if (aResponseCase_ == 7) {
       return (farm.nurture.farm.service.proto.AddBloodResponse) aResponse_;
    }
    return farm.nurture.farm.service.proto.AddBloodResponse.getDefaultInstance();
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodResponse resAddBlood = 7;</code>
   */
  public farm.nurture.farm.service.proto.AddBloodResponseOrBuilder getResAddBloodOrBuilder() {
    if (aResponseCase_ == 7) {
       return (farm.nurture.farm.service.proto.AddBloodResponse) aResponse_;
    }
    return farm.nurture.farm.service.proto.AddBloodResponse.getDefaultInstance();
  }

  public static final int RESADDBLOODBULK_FIELD_NUMBER = 8;
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodResponse resAddBloodBulk = 8;</code>
   */
  public boolean hasResAddBloodBulk() {
    return aResponseCase_ == 8;
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodResponse resAddBloodBulk = 8;</code>
   */
  public farm.nurture.farm.service.proto.BulkAddBloodResponse getResAddBloodBulk() {
    if (aResponseCase_ == 8) {
       return (farm.nurture.farm.service.proto.BulkAddBloodResponse) aResponse_;
    }
    return farm.nurture.farm.service.proto.BulkAddBloodResponse.getDefaultInstance();
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodResponse resAddBloodBulk = 8;</code>
   */
  public farm.nurture.farm.service.proto.BulkAddBloodResponseOrBuilder getResAddBloodBulkOrBuilder() {
    if (aResponseCase_ == 8) {
       return (farm.nurture.farm.service.proto.BulkAddBloodResponse) aResponse_;
    }
    return farm.nurture.farm.service.proto.BulkAddBloodResponse.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIndexBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, index_);
    }
    if (status_ != null) {
      output.writeMessage(2, getStatus());
    }
    if (aResponseCase_ == 3) {
      output.writeMessage(3, (farm.nurture.farm.service.proto.FindPasswordResponse) aResponse_);
    }
    if (aResponseCase_ == 4) {
      output.writeMessage(4, (farm.nurture.farm.service.proto.AddUserResponse) aResponse_);
    }
    if (aResponseCase_ == 5) {
      output.writeMessage(5, (farm.nurture.farm.service.proto.BulkAddUserResponse) aResponse_);
    }
    if (aResponseCase_ == 6) {
      output.writeMessage(6, (farm.nurture.farm.service.proto.FindBloodResponse) aResponse_);
    }
    if (aResponseCase_ == 7) {
      output.writeMessage(7, (farm.nurture.farm.service.proto.AddBloodResponse) aResponse_);
    }
    if (aResponseCase_ == 8) {
      output.writeMessage(8, (farm.nurture.farm.service.proto.BulkAddBloodResponse) aResponse_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIndexBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, index_);
    }
    if (status_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getStatus());
    }
    if (aResponseCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (farm.nurture.farm.service.proto.FindPasswordResponse) aResponse_);
    }
    if (aResponseCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (farm.nurture.farm.service.proto.AddUserResponse) aResponse_);
    }
    if (aResponseCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (farm.nurture.farm.service.proto.BulkAddUserResponse) aResponse_);
    }
    if (aResponseCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (farm.nurture.farm.service.proto.FindBloodResponse) aResponse_);
    }
    if (aResponseCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (farm.nurture.farm.service.proto.AddBloodResponse) aResponse_);
    }
    if (aResponseCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (farm.nurture.farm.service.proto.BulkAddBloodResponse) aResponse_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof farm.nurture.farm.service.proto.Response)) {
      return super.equals(obj);
    }
    farm.nurture.farm.service.proto.Response other = (farm.nurture.farm.service.proto.Response) obj;

    boolean result = true;
    result = result && getIndex()
        .equals(other.getIndex());
    result = result && (hasStatus() == other.hasStatus());
    if (hasStatus()) {
      result = result && getStatus()
          .equals(other.getStatus());
    }
    result = result && getAResponseCase().equals(
        other.getAResponseCase());
    if (!result) return false;
    switch (aResponseCase_) {
      case 3:
        result = result && getResFindPassword()
            .equals(other.getResFindPassword());
        break;
      case 4:
        result = result && getResAddUser()
            .equals(other.getResAddUser());
        break;
      case 5:
        result = result && getResAddUserBulk()
            .equals(other.getResAddUserBulk());
        break;
      case 6:
        result = result && getResFindBlood()
            .equals(other.getResFindBlood());
        break;
      case 7:
        result = result && getResAddBlood()
            .equals(other.getResAddBlood());
        break;
      case 8:
        result = result && getResAddBloodBulk()
            .equals(other.getResAddBloodBulk());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getIndex().hashCode();
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    switch (aResponseCase_) {
      case 3:
        hash = (37 * hash) + RESFINDPASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getResFindPassword().hashCode();
        break;
      case 4:
        hash = (37 * hash) + RESADDUSER_FIELD_NUMBER;
        hash = (53 * hash) + getResAddUser().hashCode();
        break;
      case 5:
        hash = (37 * hash) + RESADDUSERBULK_FIELD_NUMBER;
        hash = (53 * hash) + getResAddUserBulk().hashCode();
        break;
      case 6:
        hash = (37 * hash) + RESFINDBLOOD_FIELD_NUMBER;
        hash = (53 * hash) + getResFindBlood().hashCode();
        break;
      case 7:
        hash = (37 * hash) + RESADDBLOOD_FIELD_NUMBER;
        hash = (53 * hash) + getResAddBlood().hashCode();
        break;
      case 8:
        hash = (37 * hash) + RESADDBLOODBULK_FIELD_NUMBER;
        hash = (53 * hash) + getResAddBloodBulk().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static farm.nurture.farm.service.proto.Response parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static farm.nurture.farm.service.proto.Response parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.Response parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static farm.nurture.farm.service.proto.Response parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.Response parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static farm.nurture.farm.service.proto.Response parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.Response parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static farm.nurture.farm.service.proto.Response parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.Response parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static farm.nurture.farm.service.proto.Response parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.Response parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static farm.nurture.farm.service.proto.Response parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(farm.nurture.farm.service.proto.Response prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code farm.nurture.core.contracts.BloodBankSystemService.Response}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:farm.nurture.core.contracts.BloodBankSystemService.Response)
      farm.nurture.farm.service.proto.ResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              farm.nurture.farm.service.proto.Response.class, farm.nurture.farm.service.proto.Response.Builder.class);
    }

    // Construct using farm.nurture.farm.service.proto.Response.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      index_ = "";

      if (statusBuilder_ == null) {
        status_ = null;
      } else {
        status_ = null;
        statusBuilder_ = null;
      }
      aResponseCase_ = 0;
      aResponse_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_Response_descriptor;
    }

    @java.lang.Override
    public farm.nurture.farm.service.proto.Response getDefaultInstanceForType() {
      return farm.nurture.farm.service.proto.Response.getDefaultInstance();
    }

    @java.lang.Override
    public farm.nurture.farm.service.proto.Response build() {
      farm.nurture.farm.service.proto.Response result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public farm.nurture.farm.service.proto.Response buildPartial() {
      farm.nurture.farm.service.proto.Response result = new farm.nurture.farm.service.proto.Response(this);
      result.index_ = index_;
      if (statusBuilder_ == null) {
        result.status_ = status_;
      } else {
        result.status_ = statusBuilder_.build();
      }
      if (aResponseCase_ == 3) {
        if (resFindPasswordBuilder_ == null) {
          result.aResponse_ = aResponse_;
        } else {
          result.aResponse_ = resFindPasswordBuilder_.build();
        }
      }
      if (aResponseCase_ == 4) {
        if (resAddUserBuilder_ == null) {
          result.aResponse_ = aResponse_;
        } else {
          result.aResponse_ = resAddUserBuilder_.build();
        }
      }
      if (aResponseCase_ == 5) {
        if (resAddUserBulkBuilder_ == null) {
          result.aResponse_ = aResponse_;
        } else {
          result.aResponse_ = resAddUserBulkBuilder_.build();
        }
      }
      if (aResponseCase_ == 6) {
        if (resFindBloodBuilder_ == null) {
          result.aResponse_ = aResponse_;
        } else {
          result.aResponse_ = resFindBloodBuilder_.build();
        }
      }
      if (aResponseCase_ == 7) {
        if (resAddBloodBuilder_ == null) {
          result.aResponse_ = aResponse_;
        } else {
          result.aResponse_ = resAddBloodBuilder_.build();
        }
      }
      if (aResponseCase_ == 8) {
        if (resAddBloodBulkBuilder_ == null) {
          result.aResponse_ = aResponse_;
        } else {
          result.aResponse_ = resAddBloodBulkBuilder_.build();
        }
      }
      result.aResponseCase_ = aResponseCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof farm.nurture.farm.service.proto.Response) {
        return mergeFrom((farm.nurture.farm.service.proto.Response)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(farm.nurture.farm.service.proto.Response other) {
      if (other == farm.nurture.farm.service.proto.Response.getDefaultInstance()) return this;
      if (!other.getIndex().isEmpty()) {
        index_ = other.index_;
        onChanged();
      }
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      switch (other.getAResponseCase()) {
        case RESFINDPASSWORD: {
          mergeResFindPassword(other.getResFindPassword());
          break;
        }
        case RESADDUSER: {
          mergeResAddUser(other.getResAddUser());
          break;
        }
        case RESADDUSERBULK: {
          mergeResAddUserBulk(other.getResAddUserBulk());
          break;
        }
        case RESFINDBLOOD: {
          mergeResFindBlood(other.getResFindBlood());
          break;
        }
        case RESADDBLOOD: {
          mergeResAddBlood(other.getResAddBlood());
          break;
        }
        case RESADDBLOODBULK: {
          mergeResAddBloodBulk(other.getResAddBloodBulk());
          break;
        }
        case ARESPONSE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      farm.nurture.farm.service.proto.Response parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (farm.nurture.farm.service.proto.Response) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int aResponseCase_ = 0;
    private java.lang.Object aResponse_;
    public AResponseCase
        getAResponseCase() {
      return AResponseCase.forNumber(
          aResponseCase_);
    }

    public Builder clearAResponse() {
      aResponseCase_ = 0;
      aResponse_ = null;
      onChanged();
      return this;
    }


    private java.lang.Object index_ = "";
    /**
     * <code>string index = 1;</code>
     */
    public java.lang.String getIndex() {
      java.lang.Object ref = index_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        index_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string index = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIndexBytes() {
      java.lang.Object ref = index_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        index_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string index = 1;</code>
     */
    public Builder setIndex(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      index_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string index = 1;</code>
     */
    public Builder clearIndex() {
      
      index_ = getDefaultInstance().getIndex();
      onChanged();
      return this;
    }
    /**
     * <code>string index = 1;</code>
     */
    public Builder setIndexBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      index_ = value;
      onChanged();
      return this;
    }

    private farm.nurture.farm.service.proto.Status status_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.Status, farm.nurture.farm.service.proto.Status.Builder, farm.nurture.farm.service.proto.StatusOrBuilder> statusBuilder_;
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 2;</code>
     */
    public boolean hasStatus() {
      return statusBuilder_ != null || status_ != null;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 2;</code>
     */
    public farm.nurture.farm.service.proto.Status getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? farm.nurture.farm.service.proto.Status.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 2;</code>
     */
    public Builder setStatus(farm.nurture.farm.service.proto.Status value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 2;</code>
     */
    public Builder setStatus(
        farm.nurture.farm.service.proto.Status.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 2;</code>
     */
    public Builder mergeStatus(farm.nurture.farm.service.proto.Status value) {
      if (statusBuilder_ == null) {
        if (status_ != null) {
          status_ =
            farm.nurture.farm.service.proto.Status.newBuilder(status_).mergeFrom(value).buildPartial();
        } else {
          status_ = value;
        }
        onChanged();
      } else {
        statusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 2;</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        status_ = null;
        onChanged();
      } else {
        status_ = null;
        statusBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 2;</code>
     */
    public farm.nurture.farm.service.proto.Status.Builder getStatusBuilder() {
      
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 2;</code>
     */
    public farm.nurture.farm.service.proto.StatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            farm.nurture.farm.service.proto.Status.getDefaultInstance() : status_;
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.Status status = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.Status, farm.nurture.farm.service.proto.Status.Builder, farm.nurture.farm.service.proto.StatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            farm.nurture.farm.service.proto.Status, farm.nurture.farm.service.proto.Status.Builder, farm.nurture.farm.service.proto.StatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.FindPasswordResponse, farm.nurture.farm.service.proto.FindPasswordResponse.Builder, farm.nurture.farm.service.proto.FindPasswordResponseOrBuilder> resFindPasswordBuilder_;
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordResponse resFindPassword = 3;</code>
     */
    public boolean hasResFindPassword() {
      return aResponseCase_ == 3;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordResponse resFindPassword = 3;</code>
     */
    public farm.nurture.farm.service.proto.FindPasswordResponse getResFindPassword() {
      if (resFindPasswordBuilder_ == null) {
        if (aResponseCase_ == 3) {
          return (farm.nurture.farm.service.proto.FindPasswordResponse) aResponse_;
        }
        return farm.nurture.farm.service.proto.FindPasswordResponse.getDefaultInstance();
      } else {
        if (aResponseCase_ == 3) {
          return resFindPasswordBuilder_.getMessage();
        }
        return farm.nurture.farm.service.proto.FindPasswordResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordResponse resFindPassword = 3;</code>
     */
    public Builder setResFindPassword(farm.nurture.farm.service.proto.FindPasswordResponse value) {
      if (resFindPasswordBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        aResponse_ = value;
        onChanged();
      } else {
        resFindPasswordBuilder_.setMessage(value);
      }
      aResponseCase_ = 3;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordResponse resFindPassword = 3;</code>
     */
    public Builder setResFindPassword(
        farm.nurture.farm.service.proto.FindPasswordResponse.Builder builderForValue) {
      if (resFindPasswordBuilder_ == null) {
        aResponse_ = builderForValue.build();
        onChanged();
      } else {
        resFindPasswordBuilder_.setMessage(builderForValue.build());
      }
      aResponseCase_ = 3;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordResponse resFindPassword = 3;</code>
     */
    public Builder mergeResFindPassword(farm.nurture.farm.service.proto.FindPasswordResponse value) {
      if (resFindPasswordBuilder_ == null) {
        if (aResponseCase_ == 3 &&
            aResponse_ != farm.nurture.farm.service.proto.FindPasswordResponse.getDefaultInstance()) {
          aResponse_ = farm.nurture.farm.service.proto.FindPasswordResponse.newBuilder((farm.nurture.farm.service.proto.FindPasswordResponse) aResponse_)
              .mergeFrom(value).buildPartial();
        } else {
          aResponse_ = value;
        }
        onChanged();
      } else {
        if (aResponseCase_ == 3) {
          resFindPasswordBuilder_.mergeFrom(value);
        }
        resFindPasswordBuilder_.setMessage(value);
      }
      aResponseCase_ = 3;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordResponse resFindPassword = 3;</code>
     */
    public Builder clearResFindPassword() {
      if (resFindPasswordBuilder_ == null) {
        if (aResponseCase_ == 3) {
          aResponseCase_ = 0;
          aResponse_ = null;
          onChanged();
        }
      } else {
        if (aResponseCase_ == 3) {
          aResponseCase_ = 0;
          aResponse_ = null;
        }
        resFindPasswordBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordResponse resFindPassword = 3;</code>
     */
    public farm.nurture.farm.service.proto.FindPasswordResponse.Builder getResFindPasswordBuilder() {
      return getResFindPasswordFieldBuilder().getBuilder();
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordResponse resFindPassword = 3;</code>
     */
    public farm.nurture.farm.service.proto.FindPasswordResponseOrBuilder getResFindPasswordOrBuilder() {
      if ((aResponseCase_ == 3) && (resFindPasswordBuilder_ != null)) {
        return resFindPasswordBuilder_.getMessageOrBuilder();
      } else {
        if (aResponseCase_ == 3) {
          return (farm.nurture.farm.service.proto.FindPasswordResponse) aResponse_;
        }
        return farm.nurture.farm.service.proto.FindPasswordResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindPasswordResponse resFindPassword = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.FindPasswordResponse, farm.nurture.farm.service.proto.FindPasswordResponse.Builder, farm.nurture.farm.service.proto.FindPasswordResponseOrBuilder> 
        getResFindPasswordFieldBuilder() {
      if (resFindPasswordBuilder_ == null) {
        if (!(aResponseCase_ == 3)) {
          aResponse_ = farm.nurture.farm.service.proto.FindPasswordResponse.getDefaultInstance();
        }
        resFindPasswordBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            farm.nurture.farm.service.proto.FindPasswordResponse, farm.nurture.farm.service.proto.FindPasswordResponse.Builder, farm.nurture.farm.service.proto.FindPasswordResponseOrBuilder>(
                (farm.nurture.farm.service.proto.FindPasswordResponse) aResponse_,
                getParentForChildren(),
                isClean());
        aResponse_ = null;
      }
      aResponseCase_ = 3;
      onChanged();;
      return resFindPasswordBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.AddUserResponse, farm.nurture.farm.service.proto.AddUserResponse.Builder, farm.nurture.farm.service.proto.AddUserResponseOrBuilder> resAddUserBuilder_;
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse resAddUser = 4;</code>
     */
    public boolean hasResAddUser() {
      return aResponseCase_ == 4;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse resAddUser = 4;</code>
     */
    public farm.nurture.farm.service.proto.AddUserResponse getResAddUser() {
      if (resAddUserBuilder_ == null) {
        if (aResponseCase_ == 4) {
          return (farm.nurture.farm.service.proto.AddUserResponse) aResponse_;
        }
        return farm.nurture.farm.service.proto.AddUserResponse.getDefaultInstance();
      } else {
        if (aResponseCase_ == 4) {
          return resAddUserBuilder_.getMessage();
        }
        return farm.nurture.farm.service.proto.AddUserResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse resAddUser = 4;</code>
     */
    public Builder setResAddUser(farm.nurture.farm.service.proto.AddUserResponse value) {
      if (resAddUserBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        aResponse_ = value;
        onChanged();
      } else {
        resAddUserBuilder_.setMessage(value);
      }
      aResponseCase_ = 4;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse resAddUser = 4;</code>
     */
    public Builder setResAddUser(
        farm.nurture.farm.service.proto.AddUserResponse.Builder builderForValue) {
      if (resAddUserBuilder_ == null) {
        aResponse_ = builderForValue.build();
        onChanged();
      } else {
        resAddUserBuilder_.setMessage(builderForValue.build());
      }
      aResponseCase_ = 4;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse resAddUser = 4;</code>
     */
    public Builder mergeResAddUser(farm.nurture.farm.service.proto.AddUserResponse value) {
      if (resAddUserBuilder_ == null) {
        if (aResponseCase_ == 4 &&
            aResponse_ != farm.nurture.farm.service.proto.AddUserResponse.getDefaultInstance()) {
          aResponse_ = farm.nurture.farm.service.proto.AddUserResponse.newBuilder((farm.nurture.farm.service.proto.AddUserResponse) aResponse_)
              .mergeFrom(value).buildPartial();
        } else {
          aResponse_ = value;
        }
        onChanged();
      } else {
        if (aResponseCase_ == 4) {
          resAddUserBuilder_.mergeFrom(value);
        }
        resAddUserBuilder_.setMessage(value);
      }
      aResponseCase_ = 4;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse resAddUser = 4;</code>
     */
    public Builder clearResAddUser() {
      if (resAddUserBuilder_ == null) {
        if (aResponseCase_ == 4) {
          aResponseCase_ = 0;
          aResponse_ = null;
          onChanged();
        }
      } else {
        if (aResponseCase_ == 4) {
          aResponseCase_ = 0;
          aResponse_ = null;
        }
        resAddUserBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse resAddUser = 4;</code>
     */
    public farm.nurture.farm.service.proto.AddUserResponse.Builder getResAddUserBuilder() {
      return getResAddUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse resAddUser = 4;</code>
     */
    public farm.nurture.farm.service.proto.AddUserResponseOrBuilder getResAddUserOrBuilder() {
      if ((aResponseCase_ == 4) && (resAddUserBuilder_ != null)) {
        return resAddUserBuilder_.getMessageOrBuilder();
      } else {
        if (aResponseCase_ == 4) {
          return (farm.nurture.farm.service.proto.AddUserResponse) aResponse_;
        }
        return farm.nurture.farm.service.proto.AddUserResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddUserResponse resAddUser = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.AddUserResponse, farm.nurture.farm.service.proto.AddUserResponse.Builder, farm.nurture.farm.service.proto.AddUserResponseOrBuilder> 
        getResAddUserFieldBuilder() {
      if (resAddUserBuilder_ == null) {
        if (!(aResponseCase_ == 4)) {
          aResponse_ = farm.nurture.farm.service.proto.AddUserResponse.getDefaultInstance();
        }
        resAddUserBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            farm.nurture.farm.service.proto.AddUserResponse, farm.nurture.farm.service.proto.AddUserResponse.Builder, farm.nurture.farm.service.proto.AddUserResponseOrBuilder>(
                (farm.nurture.farm.service.proto.AddUserResponse) aResponse_,
                getParentForChildren(),
                isClean());
        aResponse_ = null;
      }
      aResponseCase_ = 4;
      onChanged();;
      return resAddUserBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.BulkAddUserResponse, farm.nurture.farm.service.proto.BulkAddUserResponse.Builder, farm.nurture.farm.service.proto.BulkAddUserResponseOrBuilder> resAddUserBulkBuilder_;
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserResponse resAddUserBulk = 5;</code>
     */
    public boolean hasResAddUserBulk() {
      return aResponseCase_ == 5;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserResponse resAddUserBulk = 5;</code>
     */
    public farm.nurture.farm.service.proto.BulkAddUserResponse getResAddUserBulk() {
      if (resAddUserBulkBuilder_ == null) {
        if (aResponseCase_ == 5) {
          return (farm.nurture.farm.service.proto.BulkAddUserResponse) aResponse_;
        }
        return farm.nurture.farm.service.proto.BulkAddUserResponse.getDefaultInstance();
      } else {
        if (aResponseCase_ == 5) {
          return resAddUserBulkBuilder_.getMessage();
        }
        return farm.nurture.farm.service.proto.BulkAddUserResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserResponse resAddUserBulk = 5;</code>
     */
    public Builder setResAddUserBulk(farm.nurture.farm.service.proto.BulkAddUserResponse value) {
      if (resAddUserBulkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        aResponse_ = value;
        onChanged();
      } else {
        resAddUserBulkBuilder_.setMessage(value);
      }
      aResponseCase_ = 5;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserResponse resAddUserBulk = 5;</code>
     */
    public Builder setResAddUserBulk(
        farm.nurture.farm.service.proto.BulkAddUserResponse.Builder builderForValue) {
      if (resAddUserBulkBuilder_ == null) {
        aResponse_ = builderForValue.build();
        onChanged();
      } else {
        resAddUserBulkBuilder_.setMessage(builderForValue.build());
      }
      aResponseCase_ = 5;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserResponse resAddUserBulk = 5;</code>
     */
    public Builder mergeResAddUserBulk(farm.nurture.farm.service.proto.BulkAddUserResponse value) {
      if (resAddUserBulkBuilder_ == null) {
        if (aResponseCase_ == 5 &&
            aResponse_ != farm.nurture.farm.service.proto.BulkAddUserResponse.getDefaultInstance()) {
          aResponse_ = farm.nurture.farm.service.proto.BulkAddUserResponse.newBuilder((farm.nurture.farm.service.proto.BulkAddUserResponse) aResponse_)
              .mergeFrom(value).buildPartial();
        } else {
          aResponse_ = value;
        }
        onChanged();
      } else {
        if (aResponseCase_ == 5) {
          resAddUserBulkBuilder_.mergeFrom(value);
        }
        resAddUserBulkBuilder_.setMessage(value);
      }
      aResponseCase_ = 5;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserResponse resAddUserBulk = 5;</code>
     */
    public Builder clearResAddUserBulk() {
      if (resAddUserBulkBuilder_ == null) {
        if (aResponseCase_ == 5) {
          aResponseCase_ = 0;
          aResponse_ = null;
          onChanged();
        }
      } else {
        if (aResponseCase_ == 5) {
          aResponseCase_ = 0;
          aResponse_ = null;
        }
        resAddUserBulkBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserResponse resAddUserBulk = 5;</code>
     */
    public farm.nurture.farm.service.proto.BulkAddUserResponse.Builder getResAddUserBulkBuilder() {
      return getResAddUserBulkFieldBuilder().getBuilder();
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserResponse resAddUserBulk = 5;</code>
     */
    public farm.nurture.farm.service.proto.BulkAddUserResponseOrBuilder getResAddUserBulkOrBuilder() {
      if ((aResponseCase_ == 5) && (resAddUserBulkBuilder_ != null)) {
        return resAddUserBulkBuilder_.getMessageOrBuilder();
      } else {
        if (aResponseCase_ == 5) {
          return (farm.nurture.farm.service.proto.BulkAddUserResponse) aResponse_;
        }
        return farm.nurture.farm.service.proto.BulkAddUserResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddUserResponse resAddUserBulk = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.BulkAddUserResponse, farm.nurture.farm.service.proto.BulkAddUserResponse.Builder, farm.nurture.farm.service.proto.BulkAddUserResponseOrBuilder> 
        getResAddUserBulkFieldBuilder() {
      if (resAddUserBulkBuilder_ == null) {
        if (!(aResponseCase_ == 5)) {
          aResponse_ = farm.nurture.farm.service.proto.BulkAddUserResponse.getDefaultInstance();
        }
        resAddUserBulkBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            farm.nurture.farm.service.proto.BulkAddUserResponse, farm.nurture.farm.service.proto.BulkAddUserResponse.Builder, farm.nurture.farm.service.proto.BulkAddUserResponseOrBuilder>(
                (farm.nurture.farm.service.proto.BulkAddUserResponse) aResponse_,
                getParentForChildren(),
                isClean());
        aResponse_ = null;
      }
      aResponseCase_ = 5;
      onChanged();;
      return resAddUserBulkBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.FindBloodResponse, farm.nurture.farm.service.proto.FindBloodResponse.Builder, farm.nurture.farm.service.proto.FindBloodResponseOrBuilder> resFindBloodBuilder_;
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodResponse resFindBlood = 6;</code>
     */
    public boolean hasResFindBlood() {
      return aResponseCase_ == 6;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodResponse resFindBlood = 6;</code>
     */
    public farm.nurture.farm.service.proto.FindBloodResponse getResFindBlood() {
      if (resFindBloodBuilder_ == null) {
        if (aResponseCase_ == 6) {
          return (farm.nurture.farm.service.proto.FindBloodResponse) aResponse_;
        }
        return farm.nurture.farm.service.proto.FindBloodResponse.getDefaultInstance();
      } else {
        if (aResponseCase_ == 6) {
          return resFindBloodBuilder_.getMessage();
        }
        return farm.nurture.farm.service.proto.FindBloodResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodResponse resFindBlood = 6;</code>
     */
    public Builder setResFindBlood(farm.nurture.farm.service.proto.FindBloodResponse value) {
      if (resFindBloodBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        aResponse_ = value;
        onChanged();
      } else {
        resFindBloodBuilder_.setMessage(value);
      }
      aResponseCase_ = 6;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodResponse resFindBlood = 6;</code>
     */
    public Builder setResFindBlood(
        farm.nurture.farm.service.proto.FindBloodResponse.Builder builderForValue) {
      if (resFindBloodBuilder_ == null) {
        aResponse_ = builderForValue.build();
        onChanged();
      } else {
        resFindBloodBuilder_.setMessage(builderForValue.build());
      }
      aResponseCase_ = 6;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodResponse resFindBlood = 6;</code>
     */
    public Builder mergeResFindBlood(farm.nurture.farm.service.proto.FindBloodResponse value) {
      if (resFindBloodBuilder_ == null) {
        if (aResponseCase_ == 6 &&
            aResponse_ != farm.nurture.farm.service.proto.FindBloodResponse.getDefaultInstance()) {
          aResponse_ = farm.nurture.farm.service.proto.FindBloodResponse.newBuilder((farm.nurture.farm.service.proto.FindBloodResponse) aResponse_)
              .mergeFrom(value).buildPartial();
        } else {
          aResponse_ = value;
        }
        onChanged();
      } else {
        if (aResponseCase_ == 6) {
          resFindBloodBuilder_.mergeFrom(value);
        }
        resFindBloodBuilder_.setMessage(value);
      }
      aResponseCase_ = 6;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodResponse resFindBlood = 6;</code>
     */
    public Builder clearResFindBlood() {
      if (resFindBloodBuilder_ == null) {
        if (aResponseCase_ == 6) {
          aResponseCase_ = 0;
          aResponse_ = null;
          onChanged();
        }
      } else {
        if (aResponseCase_ == 6) {
          aResponseCase_ = 0;
          aResponse_ = null;
        }
        resFindBloodBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodResponse resFindBlood = 6;</code>
     */
    public farm.nurture.farm.service.proto.FindBloodResponse.Builder getResFindBloodBuilder() {
      return getResFindBloodFieldBuilder().getBuilder();
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodResponse resFindBlood = 6;</code>
     */
    public farm.nurture.farm.service.proto.FindBloodResponseOrBuilder getResFindBloodOrBuilder() {
      if ((aResponseCase_ == 6) && (resFindBloodBuilder_ != null)) {
        return resFindBloodBuilder_.getMessageOrBuilder();
      } else {
        if (aResponseCase_ == 6) {
          return (farm.nurture.farm.service.proto.FindBloodResponse) aResponse_;
        }
        return farm.nurture.farm.service.proto.FindBloodResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.FindBloodResponse resFindBlood = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.FindBloodResponse, farm.nurture.farm.service.proto.FindBloodResponse.Builder, farm.nurture.farm.service.proto.FindBloodResponseOrBuilder> 
        getResFindBloodFieldBuilder() {
      if (resFindBloodBuilder_ == null) {
        if (!(aResponseCase_ == 6)) {
          aResponse_ = farm.nurture.farm.service.proto.FindBloodResponse.getDefaultInstance();
        }
        resFindBloodBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            farm.nurture.farm.service.proto.FindBloodResponse, farm.nurture.farm.service.proto.FindBloodResponse.Builder, farm.nurture.farm.service.proto.FindBloodResponseOrBuilder>(
                (farm.nurture.farm.service.proto.FindBloodResponse) aResponse_,
                getParentForChildren(),
                isClean());
        aResponse_ = null;
      }
      aResponseCase_ = 6;
      onChanged();;
      return resFindBloodBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.AddBloodResponse, farm.nurture.farm.service.proto.AddBloodResponse.Builder, farm.nurture.farm.service.proto.AddBloodResponseOrBuilder> resAddBloodBuilder_;
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodResponse resAddBlood = 7;</code>
     */
    public boolean hasResAddBlood() {
      return aResponseCase_ == 7;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodResponse resAddBlood = 7;</code>
     */
    public farm.nurture.farm.service.proto.AddBloodResponse getResAddBlood() {
      if (resAddBloodBuilder_ == null) {
        if (aResponseCase_ == 7) {
          return (farm.nurture.farm.service.proto.AddBloodResponse) aResponse_;
        }
        return farm.nurture.farm.service.proto.AddBloodResponse.getDefaultInstance();
      } else {
        if (aResponseCase_ == 7) {
          return resAddBloodBuilder_.getMessage();
        }
        return farm.nurture.farm.service.proto.AddBloodResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodResponse resAddBlood = 7;</code>
     */
    public Builder setResAddBlood(farm.nurture.farm.service.proto.AddBloodResponse value) {
      if (resAddBloodBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        aResponse_ = value;
        onChanged();
      } else {
        resAddBloodBuilder_.setMessage(value);
      }
      aResponseCase_ = 7;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodResponse resAddBlood = 7;</code>
     */
    public Builder setResAddBlood(
        farm.nurture.farm.service.proto.AddBloodResponse.Builder builderForValue) {
      if (resAddBloodBuilder_ == null) {
        aResponse_ = builderForValue.build();
        onChanged();
      } else {
        resAddBloodBuilder_.setMessage(builderForValue.build());
      }
      aResponseCase_ = 7;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodResponse resAddBlood = 7;</code>
     */
    public Builder mergeResAddBlood(farm.nurture.farm.service.proto.AddBloodResponse value) {
      if (resAddBloodBuilder_ == null) {
        if (aResponseCase_ == 7 &&
            aResponse_ != farm.nurture.farm.service.proto.AddBloodResponse.getDefaultInstance()) {
          aResponse_ = farm.nurture.farm.service.proto.AddBloodResponse.newBuilder((farm.nurture.farm.service.proto.AddBloodResponse) aResponse_)
              .mergeFrom(value).buildPartial();
        } else {
          aResponse_ = value;
        }
        onChanged();
      } else {
        if (aResponseCase_ == 7) {
          resAddBloodBuilder_.mergeFrom(value);
        }
        resAddBloodBuilder_.setMessage(value);
      }
      aResponseCase_ = 7;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodResponse resAddBlood = 7;</code>
     */
    public Builder clearResAddBlood() {
      if (resAddBloodBuilder_ == null) {
        if (aResponseCase_ == 7) {
          aResponseCase_ = 0;
          aResponse_ = null;
          onChanged();
        }
      } else {
        if (aResponseCase_ == 7) {
          aResponseCase_ = 0;
          aResponse_ = null;
        }
        resAddBloodBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodResponse resAddBlood = 7;</code>
     */
    public farm.nurture.farm.service.proto.AddBloodResponse.Builder getResAddBloodBuilder() {
      return getResAddBloodFieldBuilder().getBuilder();
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodResponse resAddBlood = 7;</code>
     */
    public farm.nurture.farm.service.proto.AddBloodResponseOrBuilder getResAddBloodOrBuilder() {
      if ((aResponseCase_ == 7) && (resAddBloodBuilder_ != null)) {
        return resAddBloodBuilder_.getMessageOrBuilder();
      } else {
        if (aResponseCase_ == 7) {
          return (farm.nurture.farm.service.proto.AddBloodResponse) aResponse_;
        }
        return farm.nurture.farm.service.proto.AddBloodResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.AddBloodResponse resAddBlood = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.AddBloodResponse, farm.nurture.farm.service.proto.AddBloodResponse.Builder, farm.nurture.farm.service.proto.AddBloodResponseOrBuilder> 
        getResAddBloodFieldBuilder() {
      if (resAddBloodBuilder_ == null) {
        if (!(aResponseCase_ == 7)) {
          aResponse_ = farm.nurture.farm.service.proto.AddBloodResponse.getDefaultInstance();
        }
        resAddBloodBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            farm.nurture.farm.service.proto.AddBloodResponse, farm.nurture.farm.service.proto.AddBloodResponse.Builder, farm.nurture.farm.service.proto.AddBloodResponseOrBuilder>(
                (farm.nurture.farm.service.proto.AddBloodResponse) aResponse_,
                getParentForChildren(),
                isClean());
        aResponse_ = null;
      }
      aResponseCase_ = 7;
      onChanged();;
      return resAddBloodBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.BulkAddBloodResponse, farm.nurture.farm.service.proto.BulkAddBloodResponse.Builder, farm.nurture.farm.service.proto.BulkAddBloodResponseOrBuilder> resAddBloodBulkBuilder_;
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodResponse resAddBloodBulk = 8;</code>
     */
    public boolean hasResAddBloodBulk() {
      return aResponseCase_ == 8;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodResponse resAddBloodBulk = 8;</code>
     */
    public farm.nurture.farm.service.proto.BulkAddBloodResponse getResAddBloodBulk() {
      if (resAddBloodBulkBuilder_ == null) {
        if (aResponseCase_ == 8) {
          return (farm.nurture.farm.service.proto.BulkAddBloodResponse) aResponse_;
        }
        return farm.nurture.farm.service.proto.BulkAddBloodResponse.getDefaultInstance();
      } else {
        if (aResponseCase_ == 8) {
          return resAddBloodBulkBuilder_.getMessage();
        }
        return farm.nurture.farm.service.proto.BulkAddBloodResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodResponse resAddBloodBulk = 8;</code>
     */
    public Builder setResAddBloodBulk(farm.nurture.farm.service.proto.BulkAddBloodResponse value) {
      if (resAddBloodBulkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        aResponse_ = value;
        onChanged();
      } else {
        resAddBloodBulkBuilder_.setMessage(value);
      }
      aResponseCase_ = 8;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodResponse resAddBloodBulk = 8;</code>
     */
    public Builder setResAddBloodBulk(
        farm.nurture.farm.service.proto.BulkAddBloodResponse.Builder builderForValue) {
      if (resAddBloodBulkBuilder_ == null) {
        aResponse_ = builderForValue.build();
        onChanged();
      } else {
        resAddBloodBulkBuilder_.setMessage(builderForValue.build());
      }
      aResponseCase_ = 8;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodResponse resAddBloodBulk = 8;</code>
     */
    public Builder mergeResAddBloodBulk(farm.nurture.farm.service.proto.BulkAddBloodResponse value) {
      if (resAddBloodBulkBuilder_ == null) {
        if (aResponseCase_ == 8 &&
            aResponse_ != farm.nurture.farm.service.proto.BulkAddBloodResponse.getDefaultInstance()) {
          aResponse_ = farm.nurture.farm.service.proto.BulkAddBloodResponse.newBuilder((farm.nurture.farm.service.proto.BulkAddBloodResponse) aResponse_)
              .mergeFrom(value).buildPartial();
        } else {
          aResponse_ = value;
        }
        onChanged();
      } else {
        if (aResponseCase_ == 8) {
          resAddBloodBulkBuilder_.mergeFrom(value);
        }
        resAddBloodBulkBuilder_.setMessage(value);
      }
      aResponseCase_ = 8;
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodResponse resAddBloodBulk = 8;</code>
     */
    public Builder clearResAddBloodBulk() {
      if (resAddBloodBulkBuilder_ == null) {
        if (aResponseCase_ == 8) {
          aResponseCase_ = 0;
          aResponse_ = null;
          onChanged();
        }
      } else {
        if (aResponseCase_ == 8) {
          aResponseCase_ = 0;
          aResponse_ = null;
        }
        resAddBloodBulkBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodResponse resAddBloodBulk = 8;</code>
     */
    public farm.nurture.farm.service.proto.BulkAddBloodResponse.Builder getResAddBloodBulkBuilder() {
      return getResAddBloodBulkFieldBuilder().getBuilder();
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodResponse resAddBloodBulk = 8;</code>
     */
    public farm.nurture.farm.service.proto.BulkAddBloodResponseOrBuilder getResAddBloodBulkOrBuilder() {
      if ((aResponseCase_ == 8) && (resAddBloodBulkBuilder_ != null)) {
        return resAddBloodBulkBuilder_.getMessageOrBuilder();
      } else {
        if (aResponseCase_ == 8) {
          return (farm.nurture.farm.service.proto.BulkAddBloodResponse) aResponse_;
        }
        return farm.nurture.farm.service.proto.BulkAddBloodResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.BulkAddBloodResponse resAddBloodBulk = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        farm.nurture.farm.service.proto.BulkAddBloodResponse, farm.nurture.farm.service.proto.BulkAddBloodResponse.Builder, farm.nurture.farm.service.proto.BulkAddBloodResponseOrBuilder> 
        getResAddBloodBulkFieldBuilder() {
      if (resAddBloodBulkBuilder_ == null) {
        if (!(aResponseCase_ == 8)) {
          aResponse_ = farm.nurture.farm.service.proto.BulkAddBloodResponse.getDefaultInstance();
        }
        resAddBloodBulkBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            farm.nurture.farm.service.proto.BulkAddBloodResponse, farm.nurture.farm.service.proto.BulkAddBloodResponse.Builder, farm.nurture.farm.service.proto.BulkAddBloodResponseOrBuilder>(
                (farm.nurture.farm.service.proto.BulkAddBloodResponse) aResponse_,
                getParentForChildren(),
                isClean());
        aResponse_ = null;
      }
      aResponseCase_ = 8;
      onChanged();;
      return resAddBloodBulkBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:farm.nurture.core.contracts.BloodBankSystemService.Response)
  }

  // @@protoc_insertion_point(class_scope:farm.nurture.core.contracts.BloodBankSystemService.Response)
  private static final farm.nurture.farm.service.proto.Response DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new farm.nurture.farm.service.proto.Response();
  }

  public static farm.nurture.farm.service.proto.Response getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Response>
      PARSER = new com.google.protobuf.AbstractParser<Response>() {
    @java.lang.Override
    public Response parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Response(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Response> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Response> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public farm.nurture.farm.service.proto.Response getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

