// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blood_bank_system_service.proto

package farm.nurture.farm.service.proto;

/**
 * Protobuf type {@code farm.nurture.core.contracts.BloodBankSystemService.Status}
 */
public  final class Status extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:farm.nurture.core.contracts.BloodBankSystemService.Status)
    StatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Status.newBuilder() to construct.
  private Status(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Status() {
    status_ = 0;
    errorMessages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    internalErrorCode_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Status(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              errorMessages_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            errorMessages_.add(s);
            break;
          }
          case 24: {

            internalErrorCode_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        errorMessages_ = errorMessages_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_Status_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_Status_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            farm.nurture.farm.service.proto.Status.class, farm.nurture.farm.service.proto.Status.Builder.class);
  }

  private int bitField0_;
  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.StatusCode status = 1;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.StatusCode status = 1;</code>
   */
  public farm.nurture.farm.service.proto.StatusCode getStatus() {
    @SuppressWarnings("deprecation")
    farm.nurture.farm.service.proto.StatusCode result = farm.nurture.farm.service.proto.StatusCode.valueOf(status_);
    return result == null ? farm.nurture.farm.service.proto.StatusCode.UNRECOGNIZED : result;
  }

  public static final int ERROR_MESSAGES_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList errorMessages_;
  /**
   * <code>repeated string error_messages = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getErrorMessagesList() {
    return errorMessages_;
  }
  /**
   * <code>repeated string error_messages = 2;</code>
   */
  public int getErrorMessagesCount() {
    return errorMessages_.size();
  }
  /**
   * <code>repeated string error_messages = 2;</code>
   */
  public java.lang.String getErrorMessages(int index) {
    return errorMessages_.get(index);
  }
  /**
   * <code>repeated string error_messages = 2;</code>
   */
  public com.google.protobuf.ByteString
      getErrorMessagesBytes(int index) {
    return errorMessages_.getByteString(index);
  }

  public static final int INTERNAL_ERROR_CODE_FIELD_NUMBER = 3;
  private int internalErrorCode_;
  /**
   * <code>int32 internal_error_code = 3;</code>
   */
  public int getInternalErrorCode() {
    return internalErrorCode_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != farm.nurture.farm.service.proto.StatusCode.SUCCESS.getNumber()) {
      output.writeEnum(1, status_);
    }
    for (int i = 0; i < errorMessages_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorMessages_.getRaw(i));
    }
    if (internalErrorCode_ != 0) {
      output.writeInt32(3, internalErrorCode_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != farm.nurture.farm.service.proto.StatusCode.SUCCESS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, status_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < errorMessages_.size(); i++) {
        dataSize += computeStringSizeNoTag(errorMessages_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getErrorMessagesList().size();
    }
    if (internalErrorCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, internalErrorCode_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof farm.nurture.farm.service.proto.Status)) {
      return super.equals(obj);
    }
    farm.nurture.farm.service.proto.Status other = (farm.nurture.farm.service.proto.Status) obj;

    boolean result = true;
    result = result && status_ == other.status_;
    result = result && getErrorMessagesList()
        .equals(other.getErrorMessagesList());
    result = result && (getInternalErrorCode()
        == other.getInternalErrorCode());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (getErrorMessagesCount() > 0) {
      hash = (37 * hash) + ERROR_MESSAGES_FIELD_NUMBER;
      hash = (53 * hash) + getErrorMessagesList().hashCode();
    }
    hash = (37 * hash) + INTERNAL_ERROR_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getInternalErrorCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static farm.nurture.farm.service.proto.Status parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static farm.nurture.farm.service.proto.Status parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.Status parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static farm.nurture.farm.service.proto.Status parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.Status parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static farm.nurture.farm.service.proto.Status parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.Status parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static farm.nurture.farm.service.proto.Status parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.Status parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static farm.nurture.farm.service.proto.Status parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static farm.nurture.farm.service.proto.Status parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static farm.nurture.farm.service.proto.Status parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(farm.nurture.farm.service.proto.Status prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code farm.nurture.core.contracts.BloodBankSystemService.Status}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:farm.nurture.core.contracts.BloodBankSystemService.Status)
      farm.nurture.farm.service.proto.StatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_Status_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_Status_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              farm.nurture.farm.service.proto.Status.class, farm.nurture.farm.service.proto.Status.Builder.class);
    }

    // Construct using farm.nurture.farm.service.proto.Status.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      status_ = 0;

      errorMessages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      internalErrorCode_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return farm.nurture.farm.service.proto.BloodBankSystemServiceOuterClass.internal_static_farm_nurture_core_contracts_BloodBankSystemService_Status_descriptor;
    }

    @java.lang.Override
    public farm.nurture.farm.service.proto.Status getDefaultInstanceForType() {
      return farm.nurture.farm.service.proto.Status.getDefaultInstance();
    }

    @java.lang.Override
    public farm.nurture.farm.service.proto.Status build() {
      farm.nurture.farm.service.proto.Status result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public farm.nurture.farm.service.proto.Status buildPartial() {
      farm.nurture.farm.service.proto.Status result = new farm.nurture.farm.service.proto.Status(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.status_ = status_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        errorMessages_ = errorMessages_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.errorMessages_ = errorMessages_;
      result.internalErrorCode_ = internalErrorCode_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof farm.nurture.farm.service.proto.Status) {
        return mergeFrom((farm.nurture.farm.service.proto.Status)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(farm.nurture.farm.service.proto.Status other) {
      if (other == farm.nurture.farm.service.proto.Status.getDefaultInstance()) return this;
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (!other.errorMessages_.isEmpty()) {
        if (errorMessages_.isEmpty()) {
          errorMessages_ = other.errorMessages_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureErrorMessagesIsMutable();
          errorMessages_.addAll(other.errorMessages_);
        }
        onChanged();
      }
      if (other.getInternalErrorCode() != 0) {
        setInternalErrorCode(other.getInternalErrorCode());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      farm.nurture.farm.service.proto.Status parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (farm.nurture.farm.service.proto.Status) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int status_ = 0;
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.StatusCode status = 1;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.StatusCode status = 1;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.StatusCode status = 1;</code>
     */
    public farm.nurture.farm.service.proto.StatusCode getStatus() {
      @SuppressWarnings("deprecation")
      farm.nurture.farm.service.proto.StatusCode result = farm.nurture.farm.service.proto.StatusCode.valueOf(status_);
      return result == null ? farm.nurture.farm.service.proto.StatusCode.UNRECOGNIZED : result;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.StatusCode status = 1;</code>
     */
    public Builder setStatus(farm.nurture.farm.service.proto.StatusCode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.farm.nurture.core.contracts.BloodBankSystemService.StatusCode status = 1;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList errorMessages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureErrorMessagesIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        errorMessages_ = new com.google.protobuf.LazyStringArrayList(errorMessages_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string error_messages = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getErrorMessagesList() {
      return errorMessages_.getUnmodifiableView();
    }
    /**
     * <code>repeated string error_messages = 2;</code>
     */
    public int getErrorMessagesCount() {
      return errorMessages_.size();
    }
    /**
     * <code>repeated string error_messages = 2;</code>
     */
    public java.lang.String getErrorMessages(int index) {
      return errorMessages_.get(index);
    }
    /**
     * <code>repeated string error_messages = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessagesBytes(int index) {
      return errorMessages_.getByteString(index);
    }
    /**
     * <code>repeated string error_messages = 2;</code>
     */
    public Builder setErrorMessages(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureErrorMessagesIsMutable();
      errorMessages_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string error_messages = 2;</code>
     */
    public Builder addErrorMessages(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureErrorMessagesIsMutable();
      errorMessages_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string error_messages = 2;</code>
     */
    public Builder addAllErrorMessages(
        java.lang.Iterable<java.lang.String> values) {
      ensureErrorMessagesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, errorMessages_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string error_messages = 2;</code>
     */
    public Builder clearErrorMessages() {
      errorMessages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string error_messages = 2;</code>
     */
    public Builder addErrorMessagesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureErrorMessagesIsMutable();
      errorMessages_.add(value);
      onChanged();
      return this;
    }

    private int internalErrorCode_ ;
    /**
     * <code>int32 internal_error_code = 3;</code>
     */
    public int getInternalErrorCode() {
      return internalErrorCode_;
    }
    /**
     * <code>int32 internal_error_code = 3;</code>
     */
    public Builder setInternalErrorCode(int value) {
      
      internalErrorCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 internal_error_code = 3;</code>
     */
    public Builder clearInternalErrorCode() {
      
      internalErrorCode_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:farm.nurture.core.contracts.BloodBankSystemService.Status)
  }

  // @@protoc_insertion_point(class_scope:farm.nurture.core.contracts.BloodBankSystemService.Status)
  private static final farm.nurture.farm.service.proto.Status DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new farm.nurture.farm.service.proto.Status();
  }

  public static farm.nurture.farm.service.proto.Status getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Status>
      PARSER = new com.google.protobuf.AbstractParser<Status>() {
    @java.lang.Override
    public Status parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Status(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Status> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Status> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public farm.nurture.farm.service.proto.Status getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

