// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blood_bank_system_service.proto

package farm.nurture.farm.service.proto;

public interface StatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:farm.nurture.core.contracts.BloodBankSystemService.Status)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.StatusCode status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.farm.nurture.core.contracts.BloodBankSystemService.StatusCode status = 1;</code>
   */
  farm.nurture.farm.service.proto.StatusCode getStatus();

  /**
   * <code>repeated string error_messages = 2;</code>
   */
  java.util.List<java.lang.String>
      getErrorMessagesList();
  /**
   * <code>repeated string error_messages = 2;</code>
   */
  int getErrorMessagesCount();
  /**
   * <code>repeated string error_messages = 2;</code>
   */
  java.lang.String getErrorMessages(int index);
  /**
   * <code>repeated string error_messages = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessagesBytes(int index);

  /**
   * <code>int32 internal_error_code = 3;</code>
   */
  int getInternalErrorCode();
}
